MouseLook.js refactor
overte-org/overte pull request #1004
Opened 2024-06-05 22:39 UTC by Armored-Dragon

Resolves #977 

Refactor of the existing mouseLook.js script. This refactor should make extending functionality a lot more smooth in the future.

2024-06-08 12:13 UTC, ksuprynowicz requested changes
Nice!
The refactor very nicely simplifies the code. The only thing I noticed is that variables need to be named according to our coding standards.
We also need to test this thoroughly, especially for cases such as:
 - switching from desktop to HMD mode while in mouse look
 - interactions with Inspect mode
 - login window popping up while in mouse look

2024-06-08 12:13 UTC, ksuprynowicz commented on scripts/system/controllers/mouseLook.js
> +        mouse_look_enabled = newMouseLook;
According to our coding guidelines variables should be named in mixed case:
`[1.1.3] Local variables must be in mixed case (and NOT prefixed with an underscore).`

2024-07-06 17:18 UTC, ksuprynowicz approved these changes

2024-07-06 17:21 UTC, Armored-Dragon commented
I tested this pr for a few days. All seems to be well.

2024-07-11 20:06 UTC, merged