Graphics settings
overte-org/overte pull request #1053
Opened 2024-06-29 00:05 UTC by HifiExperiments

closes #741 and #14, discussion ongoing about #740

depends on #1050

this makes bloom, haze (fog), and AO configurable in the Graphics app.  like shadows, they can all be set independently in the "custom" configuration mode, although like shadows, bloom and AO only work for the deferred renderer.  this also adds a checkbox for enabling procedural materials on models at the bottom of the Graphics settings, and changes it to default on.

- [ ] determine if we want to add tonemapping options too

2024-07-29 22:12 UTC, ksuprynowicz commented
I tested it and current version works very well.

2024-07-29 22:57 UTC, ksuprynowicz commented
One issue I noticed is that mirrors look kinda blurry even with no AA, and they always have jitter even with TAA disabled:
![image](https://github.com/user-attachments/assets/7712c569-c28d-4fe2-887a-afd80ebd5779)

2024-07-30 00:18 UTC, HifiExperiments commented
hm I'll take a look, maybe I messed up the AA controls for mirrors

2024-07-30 23:03 UTC, HifiExperiments commented
I believe I've fixed it!

2024-08-14 22:50 UTC, HifiExperiments commented
I've made a few fixes based on feedback from Alezia, but one issue that she found (which is really a problem with mirrors in general, not these changes) remains:

![image](https://github.com/user-attachments/assets/48121dce-5474-4efb-b791-bbbfcf1f3098)

when viewed at an angle, haze on skyboxes in mirrors isn't correct.  the reason for this is complicated: the technique I used for computing the mirror projection matrices distorts the depth buffer in the mirror (which is explained a bit in the paper: https://terathon.com/lengyel/Lengyel-Oblique.pdf).  in forward rendering, haze is computed when rendering the objects, so it works fine.  but in deferred rendering, haze is computed as a fullscreen pass later, and fragment positions are re-computed from the depth buffer.  this appears to be fine for most objects closer to the mirror, but it means that we are failing to properly detect which fragments are part of the skybox.  *theoretically* there are other ways we could detect the skybox, so I will have to investigate some more

2024-08-15 01:25 UTC, HifiExperiments commented on libraries/render-utils/src/DrawHaze.cpp
> +            batch.setPipeline(_separateHazePipeline);
to fix the mirror-skybox-haze problem, I've made it so that haze, when rendering in a mirror, actually renders two fullscreen passes: one with the same shader as before but only affecting shapes, and a second specialized shader that uses the stencil mask to only render over the skybox.  in this specialized shader, since we know that we're only operating on the skybox, we don't sample the linearDepthMap at all.

stencil tests should be cheap, so this should not have an impact on performance.  and this change only affects the deferred haze pass inside of mirrors; forward rendering and the main deferred pass are unaffected.

2024-08-16 02:11 UTC, HifiExperiments commented
Alezia tested the latest version and confirmed everything is working as expected!  this just needs a CR then it’ll be ready to merge

2024-08-16 21:18 UTC, daleglass requested changes
Only a few tiny complaints, great work!

2024-08-16 21:18 UTC, daleglass commented on interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
> +                                //    Render.localLightsEnabled = renderingEffectLocalLightsEnabled.checked;
This is changed, but still commented out, is that correct?

2024-08-16 21:18 UTC, daleglass commented on interface/src/Menu.cpp
> +        RenderScriptingInterface::getInstance(), SLOT(setProceduralMaterialsEnabled(bool)));
Why use the old Qt slot syntax?

2024-08-16 21:18 UTC, daleglass commented on libraries/render-utils/src/render-utils/haze.slp
> +DEFINES background:f
Missing newline at the end of file. Probably not a problem, but some things rarely have an issue with this.

2024-08-16 21:46 UTC, HifiExperiments commented on interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
> +                                //    Render.localLightsEnabled = renderingEffectLocalLightsEnabled.checked;
yeah, I just reordered these (this one used to be at the top), but this one isn't exposed in the engine like the others, so for just this one, this is still commented out and the value of the checkbox mirrors if rendering effects are enabled/disabled.  we can add it in the future

2024-08-16 21:46 UTC, HifiExperiments commented on interface/src/Menu.cpp
> +        RenderScriptingInterface::getInstance(), SLOT(setProceduralMaterialsEnabled(bool)));
this file uses a mix of the old and new syntax, I had just copied this from one nearby.  at some point we could clean up this file

2024-08-16 21:46 UTC, HifiExperiments commented on libraries/render-utils/src/render-utils/haze.slp
> +DEFINES background:f
fixed!

2024-08-17 15:03 UTC, daleglass approved these changes

2024-08-17 18:47 UTC, merged