SNAP App: support for Thumbstick of the right controller to capture picture and gif in HMD only.
overte-org/overte pull request #1090
Opened 2024-07-19 02:37 UTC by AleziaKurdis

This PR adds the possibility to click on the thumbstick of the right controller to capture picture and gif, for HMD only.

It was a bit an irritant to capture picture and have to click on the tablet to do it. It is annoying for the posture if you are in the photo and it was quite a limitation to capture in movement.

It supports at least Vive and Oculus Touch.

2024-07-22 14:33 UTC, ksuprynowicz approved these changes
Everything looks good :)

2024-07-22 14:33 UTC, ksuprynowicz commented
I think this PR is safe to merge

2024-08-03 19:47 UTC, daleglass requested changes

2024-08-03 19:47 UTC, daleglass commented on scripts/system/snapshot.js
> +    }
There should be some sort of fallback for an unrecognized controller. At least log something, so that there's some clue as to what is wrong, but preferably an user-visible error message.

Also, the XBox controller has been used for VR, so it's also a possibility.

2024-08-04 02:34 UTC, AleziaKurdis commented on scripts/system/snapshot.js
> +    }
3 things about it...
1- **Fact**: I simply bring the code from other camera app supporting the right thumb stick. **This means that the same issue exists in those app too**. 

2- **Xbox Controller**: I don't have the hardware so I wouldn't be able to test it. I have honestly not consider support larger than that for that simple reason. If you have the "**controllerType**" string and which **Controller.Standard.###** it uses, then yes, I can add it.

3-  **Unrecognized controller**: Currently, if a controller is not recognized, it simply do nothing. (No error, just not supported). The existence of this feature is not even written anywhere. This is not on the UI (a bit intentional). So people are currently find out accidentally or by learning from someone else. If a user has an unsupported controller, it won't tell him that the feature that he has never heard about before, is not working for him. He will be then as happy as all of us before this new implementation. In my opinion, It would be a bit mistake to advise directly the user that his controller is not taking change of this feature. It just cause the deception even before the need appears... It will just look clunkier as system for that user after that. 
**Instead, I would add a notice in the UI, but only if the controller is supporting it.** 

_I didn't went there cause the cost in time was a bit too much for actually just a "shortcut". 
Which means: changes in the Ui and what it needs between the app and the UI to hide/show the notice. 
I can do it. Let me know what you think about this approach._

2024-09-02 11:13 UTC, JulianGro commented
I tested this on desktop on Linux, both with and without a controller.

2024-10-02 17:37 UTC, ksuprynowicz commented on scripts/system/snapshot.js
> +    }
I think that adding a notice in the UI for supported controllers would be a really good idea.
Could you also add a TODO comment in the code telling to update this once OpenXR is merged?

2024-10-02 23:34 UTC, AleziaKurdis commented
I'm closing this PR.
- It would have to be redone if we move to openXR.
- Adding a notice means that we must redo all the UI layout (I tried and it would need significant changed to fit anything on it.)
- We have currently many camera app. Maybe we could start to consider to merge some concept in a future project. (and they are having the same limitation regarding the controlers.)
- Everyone was able to live without it before.. I think we can survive until openXr.

2024-10-02 23:34 UTC, closed without merging

2024-10-03 05:48 UTC, ksuprynowicz commented
Maybe instead of closing we should mark this as work in progress? This feature will be a very nice improvement, especially once we get OpenXR.

2024-10-04 01:24 UTC, AleziaKurdis commented
I will redo something once openXR will be there.

Also I lived at least one month with this feature... I added it mainly to be able to capture gif sequence while I was in movement, and even if the thumbstick is the closest thing to a real photography trigger, it's not a big deal for that what I aimed to do with it. Cause if we click too deep on it, it literally interrupt the movement... ruining the shot.  (it happened to me at least 25% of the time.)

I think it will worth to design a better app instead of having 5 different one. (that will all need refactoring anyway)

And the obligation to get a still image to be able to get a gif... this, i don't get it... why they coded this like that? I supposed there is a technical reason...