Automated entity property serialization
overte-org/overte pull request #1098
Opened 2024-08-07 07:25 UTC by HifiExperiments

depends on #1085, diff here: https://github.com/HifiExperiments/overte/compare/loadPriority...HifiExperiments:overte:entityProps?expand=1

thanks to @ksuprynowicz for help with cmake!

have you ever wanted to add a new entity property but you've been intimidated by all of the necessary boilerplate and different files you need to modify?  now, you just have to add a single line and all of the setup will be done for you!  I probably should have done this before I added a bunch of new properties 😓

all properties (except group properties) are now defined in EntityItemProperties.txt, which supports the following schema:
* a single word with no spaces or commas: delimits a section of properties, e.g. "Physics" or "Scripts".  after "Common", each line delimits a type of entity (e.g. "Shape", "Zone", "Web")
* TODO: individual properties
* `group:<lowercase group property name>` followed by optional `properties`, followed by a comma: represents a property group which uses the group name for scripts
    * `properties` is a space separated list which can contain any of the following:
        *   `common`: if this is a "common" group, shared by multiple entity types
        * `type:<camelcase actual type>`: some groups have a different c++ file name, e.g. `ring` is `RingGizmo`.  if this isn't specified, the group name is just capitalized, e.g. `pulse` to `Pulse`.
        * `renderUpdateOnSet`: in `setSubClassProperties`, set `_needsRenderUpdate` to true to trigger a render update if any of the group properties change
        * `recordChange`: in `setSubClassProperties`, set a member variable (e.g. `_hazePropertiesChanged`) to true if any of the group properties change
        * `customVariableSetFrom`: specifies that the class implements its own handling of how to react to changes to this group in `setSubClassProperties`
        * `customVariableRead`: specifies that the class implements its own handling of how to react to changes to this group in `readEntitySubclassDataFromBuffer`

all group properties are defined in EntityItemGroupProperties.txt, which supports the following schema:
- TODO: group properties

2024-08-07 07:30 UTC, HifiExperiments commented on libraries/networking/src/udt/PacketHeaders.h
> +    PropertyCleanup,
I originally planned to do this without making it a protocol change.  however, while digging, I realized that some reorganization was necessary (e.g. Text `unlit` was moved higher to be a common prop with the new Shape `unlit`), and some improvements were possible (e.g. we were still sending the old marketplace certification properties but they were just unused, and the Shape `shape` property was being sent over the wire as a string instead of an enum.

between all of that and just general cautiousness, seems better to make it a protocol change

2024-08-07 07:32 UTC, HifiExperiments commented
this is a bit complicated to review since the diff is almost all deletion and the actual code is generated by cmake.  the way I double checked everything as I went was to run cmake locally and compare the new output for all of the files to the files before this change.  most properties are super simple, but some have subtle tricky things about them that we need to make sure are maintained.

2024-09-07 17:15 UTC, ksuprynowicz commented
I just tested it using a copy of Overte_hub, since it's a heavy world, and everything works perfectly.

2024-09-07 17:16 UTC, ksuprynowicz commented
Would anyone else like to test it, or can we mark it as QA approved?

2024-09-09 19:40 UTC, HifiExperiments commented
(more testing is always great but I will say that for this PR, a careful code review comparing the new generated code to the old code will probably be the most effective method of catching issues, as the bugs are likely to be extremely subtle things related to some of the more complex properties like simulation ownership)

2024-09-27 22:20 UTC, ksuprynowicz commented
It looks like in EntityItemProperties.h LinePoints have moved from Polyline to Common section (l.235):
```
DEFINE_PROPERTY_REF(LinePoints, linePoints, qVectorVec3, ENTITY_ITEM_DEFAULT_EMPTY_VEC3_QVEC);
```

2024-09-27 22:31 UTC, ksuprynowicz commented
In EntityItemProperties.h shape property definition has changed from QString to EntityShape - is it intended?
```
	// Shape
	DEFINE_PROPERTY_REF_ENUM(Shape, shape, EntityShape, EntityShape::Sphere);
```
Previously:
```
    // Shape
    DEFINE_PROPERTY_REF(PROP_SHAPE, Shape, shape, QString, "Sphere");
```

2024-09-27 22:42 UTC, HifiExperiments commented
> It looks like in EntityItemProperties.h LinePoints have moved from Polyline to Common section (l.235):

yes this was intentional!  they are shared by Line and Polyline

> In EntityItemProperties.h shape property definition has changed from QString to EntityShape 

this was also intentional, it will take less space in a packet

2024-09-28 14:12 UTC, ksuprynowicz commented
I noticed that `ADD_GROUP_PROPERTY_TO_MAP_WITH_RANGE` is no longer used. Earlier it was used in things like `RingGizmoPropertyGroup`, but in the PR it's replaced with `ADD_GROUP_PROPERTY_TO_MAP`.

2024-09-28 16:27 UTC, ksuprynowicz commented
In `EntityPropertyFlags.h` `PROP_AMBIENT_LIGHT_MODE` moved from Ambient light to ambientOcclusion

2024-09-28 16:30 UTC, ksuprynowicz commented
Some other properties moved to ambientOcclusion too:
```
	PROP_SKYBOX_MODE = PROP_DERIVED_48,
	PROP_HAZE_MODE = PROP_DERIVED_49,
	PROP_BLOOM_MODE = PROP_DERIVED_50,
	PROP_AVATAR_PRIORITY = PROP_DERIVED_51,
	PROP_SCREENSHARE = PROP_DERIVED_52,
	PROP_TONEMAPPING_MODE = PROP_DERIVED_53,
```

2024-09-28 16:46 UTC, ksuprynowicz commented
In GrabPropertyGroup.h 
```
COPY_GROUP_PROPERTY_TO_QSCRIPTVALUE_IF_URL_PERMISSION(PROP_GRAB_EQUIPPABLE_INDICATOR_URL ...
```
changed to
```
COPY_GROUP_PROPERTY_TO_QSCRIPTVALUE(PROP_GRAB_EQUIPPABLE_INDICATOR_URL
```

2024-09-28 17:46 UTC, ksuprynowicz commented
In ImageEntityItem.cpp one line seems missing:
```
    withReadLock([&] {
        _pulseProperties.getProperties(properties);
        properties.setNaturalDimensions(_naturalDimensions);
    });
```
changed to
```
	withReadLock([&] {
		_pulseProperties.getProperties(properties);
	});
```

2024-09-28 17:57 UTC, ksuprynowicz commented
Is legacy property support being removed  from `KeyLightPropertyGroup::copyFromScriptValue`?

```
    // legacy property support
    COPY_PROPERTY_FROM_QSCRIPTVALUE_GETTER(keyLightColor, u8vec3Color, setColor, getColor);
    COPY_PROPERTY_FROM_QSCRIPTVALUE_GETTER(keyLightIntensity, float, setIntensity, getIntensity);
    COPY_PROPERTY_FROM_QSCRIPTVALUE_GETTER(keyLightDirection, vec3, setDirection, getDirection);
    COPY_PROPERTY_FROM_QSCRIPTVALUE_GETTER(keyLightCastShadows, bool, setCastShadows, getCastShadows);
```

2024-09-28 18:24 UTC, ksuprynowicz commented
In `LightEntityItem.cpp` it looks like `_needsRenderUpdate |= _falloffRadius != value;` is missing from `LightEntityItem::setFalloffRadius`

2024-09-28 20:35 UTC, ksuprynowicz commented
Should PolyLineEntityItem::getEntityProperties be empty?
```
EntityPropertyFlags PolyLineEntityItem::getEntityProperties(EncodeBitstreamParams& params) const {
    EntityPropertyFlags requestedProperties = EntityItem::getEntityProperties(params);

    return requestedProperties;
}
```
Previously:
```
EntityPropertyFlags PolyLineEntityItem::getEntityProperties(EncodeBitstreamParams& params) const {
    EntityPropertyFlags requestedProperties = EntityItem::getEntityProperties(params);
    requestedProperties += PROP_COLOR;
    requestedProperties += PROP_TEXTURES;

    requestedProperties += PROP_LINE_POINTS;
    requestedProperties += PROP_STROKE_WIDTHS;
    requestedProperties += PROP_STROKE_NORMALS;
    requestedProperties += PROP_STROKE_COLORS;
    requestedProperties += PROP_IS_UV_MODE_STRETCH;
    requestedProperties += PROP_LINE_GLOW;
    requestedProperties += PROP_LINE_FACE_CAMERA;
    return requestedProperties;
}
```

2024-09-28 21:44 UTC, ksuprynowicz commented
`ShapeEntityItem::getProperties` seems to be missing `properties._shapeChanged = false;`.

2024-09-29 11:01 UTC, ksuprynowicz requested changes
I love how much redundant code is removed by this PR. It will make adding new entity properties a lot easier in the future.
I reviewed all the code and compared generated files to their previous, manually-written counterparts. Almost everything looks fine, I have just a few questions that I left in earlier comments. I also thing that it would be good to document how it works to make future work on it easier, maybe in the cmake macro?

2024-09-29 22:39 UTC, HifiExperiments commented
> I noticed that `ADD_GROUP_PROPERTY_TO_MAP_WITH_RANGE` is no longer used. Earlier it was used in things like `RingGizmoPropertyGroup`, but in the PR it's replaced with `ADD_GROUP_PROPERTY_TO_MAP`.

ooo good catch, I had a copy/paste bug and min/max wasn't properly handling minus signs or `0`s

> In `EntityPropertyFlags.h` `PROP_AMBIENT_LIGHT_MODE` moved from Ambient light to ambientOcclusion
> Some other properties moved to ambientOcclusion too:
> 
> ```
> 	PROP_SKYBOX_MODE = PROP_DERIVED_48,
> 	PROP_HAZE_MODE = PROP_DERIVED_49,
> 	PROP_BLOOM_MODE = PROP_DERIVED_50,
> 	PROP_AVATAR_PRIORITY = PROP_DERIVED_51,
> 	PROP_SCREENSHARE = PROP_DERIVED_52,
> 	PROP_TONEMAPPING_MODE = PROP_DERIVED_53,
> ```

ah so this is just a comment so it doesn't really matter, but the reason it's like that is because Zones randomly have the group properties first, whereas most other types have the group properties last.  I could move the non-group properties up if we thought it was clearer, I was mostly just leaving it how it had been.

> In GrabPropertyGroup.h
> 
> ```
> COPY_GROUP_PROPERTY_TO_QSCRIPTVALUE_IF_URL_PERMISSION(PROP_GRAB_EQUIPPABLE_INDICATOR_URL ...
> ```
> 
> changed to
> 
> ```
> COPY_GROUP_PROPERTY_TO_QSCRIPTVALUE(PROP_GRAB_EQUIPPABLE_INDICATOR_URL
> ```

🙏 fixed

> Is legacy property support being removed from `KeyLightPropertyGroup::copyFromScriptValue`?

whoops, that wasn't intentional, I've put it back!

> Should PolyLineEntityItem::getEntityProperties be empty?

oof definitely not, I accidentally deleted an `S` from the end of the replacement variable name, great catch!

> `ShapeEntityItem::getProperties` seems to be missing `properties._shapeChanged = false;`.

I always wondered why that was there, `COPY_ENTITY_PROPERTY_TO_PROPERTIES` already sets this to false so it was unnecessary.

2024-09-29 22:40 UTC, HifiExperiments commented on cmake/macros/GenerateEntityProperties.cmake
> +endmacro()
great call, I've added some comments!

2024-09-29 22:42 UTC, HifiExperiments commented on libraries/entities/src/EntityItemPropertiesDocs.cpp
> +//
ah great point, how do I check this?

2024-09-30 18:08 UTC, ksuprynowicz commented on cmake/macros/GenerateEntityProperties.cmake
> +endmacro()
Thank you!

2024-09-30 21:42 UTC, ksuprynowicz commented on libraries/entities/src/EntityItemPropertiesDocs.cpp
> +//
I just checked, works perfectly :)
You need to have node.js installed and set `JSDOC_ENABLED` cmake variable, then it will build documentation. Documentation will be in `build/tools/jsdoc/out`.

2024-09-30 21:43 UTC, ksuprynowicz commented
I think it's ready to merge :)

2024-09-30 22:56 UTC, merged