Fix Create App not honoring menu bar actions
overte-org/overte pull request #1123
Opened 2024-08-27 21:12 UTC by Armored-Dragon

This implements a workaround for the Create app so that it responds to presses on the menu bar.
![Screenshot_20240827_145213](https://github.com/user-attachments/assets/d519750f-394b-4ba4-a0e0-9de333e2c1cd)

Fixes https://github.com/overte-org/overte/issues/588

2024-09-02 10:41 UTC, JulianGro commented
What exactly does this do? It sounds like this fixes the buttons on the menu bar, but the code seems to match pressing specific keys instead. Does this fix the keyboard shortcuts?

2024-09-02 17:40 UTC, Armored-Dragon commented
> What exactly does this do? It sounds like this fixes the buttons on the menu bar, but the code seems to match pressing specific keys instead. Does this fix the keyboard shortcuts?

The effective fix is to listen for the key combinations emitted by the menu bar buttons and not the menu bar buttons themselves.
[This explains a tiny bit more](https://github.com/overte-org/overte/issues/588#issuecomment-2313427665).
I have severed a lot of internal key combinations as I think they were made with the assumption that the windows "Create Tools" and "Entity List" could not emit key combinations to the entire interface? 
It even looks as if some key combinations are defined twice, for which their maybe a good reason for, but other than my guess above, I can't find anywhere the application fails off of this PR.

I have only tested this on Arch Linux desktop mode. At some point I or someone else will need to test in VR mode to make sure everything works.
Mac support was also impacted as I did remove an instance of their key press and replaced it with [a direct call to the function](https://github.com/overte-org/overte/blob/cf3afa8855843aacc2ab7842c87a12ee66ec996f/scripts/system/create/edit.js#L3158).

2024-09-29 21:22 UTC, daleglass requested changes

2024-09-29 21:22 UTC, daleglass commented on scripts/system/create/edit.js
> +        if (event.key === 16777223 && !event.isControl && !event.isShifted) {
What is 16777223? That's very strange looking.

At the very least a comment would be nice to explain where that's from.

2024-09-29 21:22 UTC, daleglass commented on scripts/system/create/edit.js
> +        if (event.key === 67 && event.isControl && !event.isShifted) {
is keyCodeString not available here? Using numeric constants is a bit obscure

2024-09-30 11:44 UTC, Armored-Dragon commented on scripts/system/create/edit.js
> +        if (event.key === 16777223 && !event.isControl && !event.isShifted) {
That is the delete key on the keyboard. The other keys are a low two digit value because they use "c" and "v". The delete key, at least on QT, is 16777223.

2024-09-30 13:05 UTC, Armored-Dragon commented on scripts/system/create/edit.js
> +        if (event.key === 67 && event.isControl && !event.isShifted) {
`.keyCodeString` is not available from the event. There is a alternative `.text` that does essentially the same thing. This has been adjusted in [this commit](https://github.com/overte-org/overte/pull/1123/commits/1ede7ed3e9ee72be055cd93b6ec57c3f247de08c).

2024-10-01 20:41 UTC, daleglass approved these changes

2024-10-05 20:33 UTC, ksuprynowicz commented
I just tested it, works perfectly :)

2024-10-05 20:33 UTC, merged