support more procedural shader uniform types, including arrays
overte-org/overte pull request #1178
Opened 2024-10-22 00:18 UTC by HifiExperiments

procedural shaders previously supported uniforms of types float, vec2, vec3, and vec4.  this PR adds support for mat3, mat4, vec3[], vec4[], mat3[], and mat4[].

[here](https://gist.github.com/HifiExperiments/55ce561345174d5edfe0c7a9670b7ebd/raw/a64d04935d8b0eb8b148985a4a577d98c0a788bb/GPUParticlesSplatter.js) is a script that demonstrates this feature.  it creates a procedural particle entity and places a new particle every time you click on an entity (up to 50 particles in this example but it would support more).  in the vertex shader, the click positions (and normals) are sent as a uniform vec3[].

2024-10-22 00:30 UTC, HifiExperiments commented on libraries/procedural/src/procedural/Procedural.cpp
> +            _slotMap.clear();
per the [spec](https://www.khronos.org/opengl/wiki/Uniform_(GLSL)), float/vec2/vec3/vec4/mat3/mat4 take up a single uniform slot, whereas array types take up as many as the length of the array.

we compute how many slots each uniform is going to need up here, and then in `Procedural::setupUniforms` we can just look it up

2024-10-22 00:30 UTC, HifiExperiments commented on libraries/procedural/src/procedural/Procedural.cpp
> +                        trueUniformName += "[0]";
due to the internals of how our shader management classes work, reflection->uniforms expects the slot to be specified for just the first element of array types, with `[0]` included at the end of the string

2024-11-01 15:41 UTC, ksuprynowicz requested changes
This is awesome :)
Could we add example script to our scripting API documentation?

2024-11-02 04:15 UTC, HifiExperiments commented
> This is awesome :) Could we add example script to our scripting API documentation?

great point, maybe the best place is to update the procedural shader guide?  I added some more info and an example here: https://github.com/overte-org/overte-docs-sphinx/pull/54

2024-11-03 21:33 UTC, ksuprynowicz commented
> great point, maybe the best place is to update the procedural shader guide? I added some more info and an example here: [overte-org/overte-docs-sphinx#54](https://github.com/overte-org/overte-docs-sphinx/pull/54)

Thank you! I think it's the best way to do it.

2024-11-03 21:33 UTC, ksuprynowicz approved these changes

2024-11-29 18:33 UTC, ksuprynowicz commented
It works really well, both in desktop mode and VR.

2024-11-29 18:33 UTC, merged