fix noNetwork and add documentation for automated entity property files
overte-org/overte pull request #1242
Opened 2024-11-17 22:06 UTC by HifiExperiments

closes #1223 

also fixes the problem with `noNetwork` that was the cause of #1222

2024-11-23 19:01 UTC, daleglass requested changes

2024-11-23 19:01 UTC, daleglass commented on cmake/macros/GenerateEntityProperties.cmake
> +        if(LINE MATCHES "#.*")
This will be a bit confusing because it'll match:

    something_useful_here # explanatory comment

I suggest:

    string(REGEX REPLACE "#.*$" "" OUT IN


As a bit better. Untested though.

2024-11-23 19:07 UTC, HifiExperiments commented on cmake/macros/GenerateEntityProperties.cmake
> +        if(LINE MATCHES "#.*")
I think what I have will only match lines beginning with #

2024-11-23 19:08 UTC, HifiExperiments commented on cmake/macros/GenerateEntityProperties.cmake
> +        if(LINE MATCHES "#.*")
ah but other lines will break if they have comments at the end, yeah I can fix that

2024-11-23 19:11 UTC, daleglass commented on cmake/macros/GenerateEntityProperties.cmake
> +        if(LINE MATCHES "#.*")
No, that will match any ocurrence of a #.

To make a regex that only matches the start of a line you need a ^. Something like this:

    ^\s*#.*

^ is the start of the line, \s* means "any number of whitepsace". I'm used to the Perl dialect, but I'm pretty sure that's universal and CMake should handle that the same.

2025-02-14 09:57 UTC, ksuprynowicz commented
Can we merge this PR?

2025-02-14 14:01 UTC, HifiExperiments commented
yeah it’s all ready for review!

2025-02-26 11:41 UTC, JulianGro approved these changes
Looks fine, except for that change I commented on and don't understand.

2025-02-26 11:41 UTC, JulianGro commented on cmake/macros/GenerateEntityProperties.cmake
> +                        string(CONCAT ${CURRENT_TYPE}_REQUESTED_PROPS "${${CURRENT_TYPE}_REQUESTED_PROPS}" "\trequestedProperties += ${ENTITY_PROPERTY_ENUM};\n")
Can you explain this change?
At first glance, it looks like you take something from being `NOT COMMON_PROPS` and `NOT (…)noNetwork(…)` and moving it to `NOT COMMON_PROPS` and `NOT LOCAL(…)`. So I don't see what this changes.

2025-03-01 07:48 UTC, HifiExperiments commented on cmake/macros/GenerateEntityProperties.cmake
> +                        string(CONCAT ${CURRENT_TYPE}_REQUESTED_PROPS "${${CURRENT_TYPE}_REQUESTED_PROPS}" "\trequestedProperties += ${ENTITY_PROPERTY_ENUM};\n")
this was the crux of the bug.  noNetwork things still need to add to `requestedProperties`, so that's why it moved out of that section.  and then if you look at the original lines (https://github.com/overte-org/overte/pull/1098/files#diff-074a03cc160e5dc50adfda4db71ff433d7f1d89e799c131119f8c0dc0e375dc7L79) before my first change, we didn't have local properties in the requestedProperties (I think because they are added automatically when the actual properties are suggested), so it's not needed for them

2025-06-10 08:07 UTC, HifiExperiments commented
this PR could use a real quick test so we can finally merge it if anyone has a sec.  really just need to confirm that entityHostType still appears in the results of Entities.getEntityProperity(<some entity ID>)

2025-06-10 23:08 UTC, ada-tv commented
(After rebasing on master because I didn't want to have to deal with vcpkg again,) `entityHostType` shows up fine in `Entities.getEntityProperties` when selected specifically but isn't in the "everything" `null` case, the same behavior as 2025.05.01

Network play looks fine too at a glance, nothing is severely broken and the hub loads fine

2025-06-10 23:37 UTC, HifiExperiments commented
cool, if the behavior is the same sounds like it’s good to merge!

thank you for testing ❤️

2025-06-11 00:32 UTC, merged