Fix voxel deadlock and improve performance
overte-org/overte pull request #140
Opened 2022-07-27 21:14 UTC by ksuprynowicz

This fixes deadlock between voxel entity code and simulation thread, and also improves performance by reducing amount of mutex locks by thousand times or more in some functions.

2022-07-27 21:36 UTC, daleglass approved these changes
Looks good to me!

2022-07-27 22:40 UTC, HifiExperiments commented on libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
> +    bool is_updated = false;
per coding standard, use camel case or just:
```suggestion
    bool changed = false;
```

2022-07-27 22:40 UTC, HifiExperiments commented on libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
> +    // TODO: could be made much more performant by moving startUpdates() to another function
is this comment right?  seems like you did move it?  is it no longer needed in this function?

2022-07-27 22:51 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR140/Overte-PR140-3f17820.tar.gz
 - https://public.overte.org/build/overte/PR140/Overte-PR140-3f17820.tar.Z
 - https://public.overte.org/build/overte/PR140/Overte-PR140-3f17820.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR140/Overte-PR140-3f17820.tar.gz
 - https://public.overte.org/build/overte/PR140/Overte-PR140-3f17820.tar.Z
 - https://public.overte.org/build/overte/PR140/Overte-PR140-3f17820.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR140/Overte-PR140-3f17820.exe

2022-07-27 23:08 UTC, ksuprynowicz commented on libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
> +    // TODO: could be made much more performant by moving startUpdates() to another function
Thanks! It's indeed already moved. I removed outdated comment :)

2022-07-28 05:01 UTC, JulianGro requested changes

2022-07-28 05:01 UTC, JulianGro commented on libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
> +            is_updated = true;
```suggestion
            changed = true;
```

2022-07-28 05:01 UTC, JulianGro commented on libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
> +    if (is_updated) {
```suggestion
    if (changed) {
```

2022-07-28 06:59 UTC, HifiExperiments approved these changes
approved pending julian’s fixes (sorry, idk how to do multi line suggestions from my phone)

2022-07-30 12:26 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.tar.Z
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.tar.gz
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.tar.gz
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.sh
 - https://public.overte.org/build/overte/PR140/Overte-PR140-e4bd58b.tar.Z

2022-07-30 12:50 UTC, ksuprynowicz commented
I tested it thouroughly on both Linux and Windows and it's ready to merge in my opinion.

2022-07-30 13:09 UTC, merged