fixed opening directories on linux
overte-org/overte pull request #142
Opened 2022-07-28 19:34 UTC by shocktail39

the first / of the file path was getting removed, causing interface to try to access a relative path instead of an absolute one.

2022-07-28 19:50 UTC, daleglass requested changes

2022-07-28 19:50 UTC, daleglass commented on interface/src/Application.cpp
> +    filepath.remove("file://");
Technically, this shouldn't be here because it's a different problem being fixed

2022-07-28 19:52 UTC, shocktail39 commented on interface/src/Application.cpp
> +    filepath.remove("file://");
ah, should i remove it and put it in its own request?

2022-07-28 19:53 UTC, daleglass commented on interface/src/Application.cpp
> +    filepath.remove("file://");
That, or you could change the description of the commit to make it clearer the change that was made

2022-07-28 19:54 UTC, shocktail39 commented on interface/src/Application.cpp
> +    filepath.remove("file://");
ok will do

2022-07-28 20:09 UTC, shocktail39 commented
needs testing on windows to make sure fixing it on linux didn't break it on windows.

2022-07-28 20:16 UTC, daleglass approved these changes

2022-07-28 21:58 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.tar.Z
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.sh
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.tar.Z
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.tar.gz
 - https://public.overte.org/build/overte/PR142/Overte-PR142-65a5f29.sh

2022-07-30 12:49 UTC, ksuprynowicz commented
It breaks uploading images by drag and drop on Windows.

2022-07-30 13:07 UTC, ksuprynowicz commented
All I get in the logs is:
```
[07/30 15:06:19] [DEBUG] [hifi.interface] An image file has been dropped in
[07/30 15:06:19] [DEBUG] [hifi.ui] setKeyboardRaised:  QQuickFlow(0x236aa55bc60) , raised:  false , numeric:  false , password:  false
[07/30 15:06:19] [WARNING] [hifi.interface] "Error downloading model: Could not upload model to the Asset Server."```

2022-07-30 16:27 UTC, shocktail39 commented
i'm not around a computer at the moment.  could someone please try reverting line 4171 back to `filepath.remove("file:///");` and see if that works on both?  i just realized that i initially determined it was "broken" in serverless, where there is no asset server to upload to.

2022-07-30 16:35 UTC, ksuprynowicz commented
Sure! I willo give it a try

2022-07-30 18:09 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.tar.Z
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.tar.gz
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.sh

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.tar.Z
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.sh
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR142/Overte-PR142-3abfb23.exe

2022-09-04 13:22 UTC, JulianGro commented
Fixed in https://github.com/overte-org/overte/pull/158
Thanks for finding the exact place where the problem occurs.

2022-09-04 13:22 UTC, closed without merging