Rebranding and fixing URLs, including CDN ones
overte-org/overte pull request #149
Opened 2022-08-03 22:36 UTC by ksuprynowicz

Environment variables are renamed too, so compatibility with tools such as Overte-builder will have to be ensured by updating said tools.

2022-08-04 00:27 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-8545984.tar.Z
 - https://public.overte.org/build/overte/PR149/Overte-PR149-8545984.sh
 - https://public.overte.org/build/overte/PR149/Overte-PR149-8545984.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-8545984.sh
 - https://public.overte.org/build/overte/PR149/Overte-PR149-8545984.tar.Z
 - https://public.overte.org/build/overte/PR149/Overte-PR149-8545984.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-8545984.exe

2022-08-07 10:11 UTC, JulianGro requested changes
Keep in mind that OVERTE_PUBLIC_CDN does not exist.
I *think* that would be https://overte-git.daleglass.dev/dale/content
But this only seems used in the script-archive and that has a lot of broken stuff anyways.

2022-08-07 10:11 UTC, JulianGro commented on pkg-scripts/overte-server.spec
> +	if [ -d "/var/lib/athena" ]; then
This script has logic to replace old servers.
Maybe we should have a prompt for replacing Vircadia servers as well.

2022-08-07 10:15 UTC, JulianGro commented on pkg-scripts/overte-server.spec
> +	if [ -d "/var/lib/athena" ]; then
Nevermind, just realized that Vircadia hasn't had RPM servers for some protocol breaks.

2022-08-07 10:22 UTC, ksuprynowicz commented
Thanks!
I didn't know this. I will fix it soon, and add more commits regarding CDN URLs. We will be working on this with Dale and I will ask him to upload missing stuff to our servers.

2022-08-08 22:16 UTC, JulianGro commented
I just enabled redirects for the docs. This means that none of the docs.overte.org URLs need the /en/latest/ part in them.

2022-08-21 11:57 UTC, JulianGro approved these changes
I approve all changes (especially the ones I made ;)

2022-09-01 18:15 UTC, ksuprynowicz commented
Why are there no builds for this one?

2022-09-01 20:31 UTC, JulianGro commented
I assume it doesn't try to build if there are merge conflicts.

2022-09-04 12:34 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-6686a03.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-6686a03.exe

2022-09-04 12:35 UTC, ksuprynowicz commented
I tested both server and client on Linux, works perfectly.

2022-09-04 21:38 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-a70a4ac.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-a70a4ac.exe

2022-09-05 20:14 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-5a815c1.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-5a815c1.exe

2022-09-06 23:28 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-c78e704.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-c78e704.exe

2022-09-08 23:04 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-b1693fd.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR149/Overte-PR149-b1693fd.exe

2022-09-09 15:23 UTC, merged

2022-09-09 15:36 UTC, JulianGro approved these changes

2022-09-09 15:36 UTC, JulianGro commented on README.md
> +* Collaborative in-game creation
```suggestion
* Collaborative in-world creation
```
Little nitpick. I remember some people being almost ready to rip my head of for calling Vircadia a game back in the day.

2022-09-09 15:42 UTC, ksuprynowicz commented on README.md
> +* Collaborative in-game creation
I think Vircadia treated itself a bit too seriously, but we can definitely change it. We would probably have to open another PR though since this one already got merged.

2022-09-09 15:52 UTC, ksuprynowicz commented on README.md
> +* Collaborative in-game creation
Right now "Commit suggestion" field is greyed out.

2022-09-09 16:22 UTC, ksuprynowicz commented on README.md
> +* Collaborative in-game creation
Also, "in-game" doesn't imply entire project being a game. From my perspective, it is kind of a very specialized game engine, with a lot of high-level features already built it. Of course I don't mind changing it to "in-world" either :)

2022-09-09 16:52 UTC, ksuprynowicz commented on README.md
> +* Collaborative in-game creation
On the other hand using "world" instead signifies that other things than just games are possible, like for example educational experiences, or various kinds of art events, so it's a good point.