Replace Graphik with Fira Sans
overte-org/overte pull request #155
Opened 2022-08-07 12:02 UTC by daleglass

Alternate fix for #153

2022-08-07 12:10 UTC, daleglass commented
Notes for testing:

RadioButton.qml contained:
`topPadding: -3 // For perfect alignment when using Graphik`

and Button.qml contained:
`topPadding: -2 // Necessary for proper alignment using Graphik Medium`

So buttons and radio buttons should be looked at to see whether some sort of padding is needed and how much. I commented the line out entirely, so alignment might be wrong with the PR as-is.

2022-08-07 12:24 UTC, ksuprynowicz requested changes

2022-08-07 12:24 UTC, ksuprynowicz commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-Medium.ttf");
File fonts/FiraSans-Medium.ttf doesn't exist.

2022-08-07 12:24 UTC, ksuprynowicz commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-Regular.ttf");
This line occurs twice

2022-08-07 12:24 UTC, ksuprynowicz commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-SemiBold.ttf");
This line occurs twice

2022-08-07 12:34 UTC, daleglass commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-Medium.ttf");
done

2022-08-07 12:36 UTC, ksuprynowicz commented
This one is ready for testing too :)

2022-08-07 13:20 UTC, ksuprynowicz commented
I tested it on Linux and didn't notice any problems.

2022-08-07 14:28 UTC, JulianGro requested changes

2022-08-07 14:28 UTC, JulianGro commented on screenshare/src/styles.css
> +  src: url("./resources/FiraSans-Regular.ttf");
According to GitHub, you changed the URL here, but there is no `./resources/FiraSans-Regular.ttf` file

2022-08-07 14:28 UTC, JulianGro commented on tools/jsdoc/hifi-jsdoc-template/static/styles/jsdoc.css
>  	src: url('../fonts/Graphik-Regular.otf') format('opentype');
This URLs need to be changed, and the font needs to be put there as well.

2022-08-07 14:28 UTC, JulianGro commented on tools/jsdoc/hifi-jsdoc-template/static/styles/jsdoc.css
>  	src: url('../fonts/Graphik-SemiBold.otf') format('opentype');
This URLs need to be changed, and the font needs to be put there as well.

2022-08-07 14:28 UTC, JulianGro commented on launchers/win32/Launcher.rc
> +IDR_FONT_REGULAR        BINARY                  "res\\FiraSansregular.ttf"
This file does not exist

2022-08-07 14:28 UTC, JulianGro commented on launchers/win32/Launcher.rc
> +IDR_FONT_BOLD           BINARY                  "res\\FiraSansbold.ttf"
This file does not exist

2022-08-07 14:28 UTC, JulianGro commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-Regular.ttf");
This file does not exist

2022-08-07 14:28 UTC, JulianGro commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-SemiBold.ttf");
This file does not exist

2022-08-07 14:33 UTC, JulianGro requested changes
The interface/resources/qml/stylesUit/GraphikMedium.qml and similar files don't get replaced.
I am pretty sure that this breaks all occurences of HifiStylesUit.FiraSansRegular

2022-08-07 15:30 UTC, daleglass commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-Regular.ttf");
It does,
```
interface/resources/fonts/FiraSans-Regular.ttf
interface/resources/fonts/FiraSans-SemiBold.ttf
```

2022-08-07 15:30 UTC, daleglass commented on interface/src/Application.cpp
> +    QFontDatabase::addApplicationFont(PathUtils::resourcesPath() + "fonts/FiraSans-SemiBold.ttf");
as above

2022-08-07 15:33 UTC, daleglass commented on launchers/win32/Launcher.rc
> +IDR_FONT_REGULAR        BINARY                  "res\\FiraSansregular.ttf"
We're not using the launcher, but okay, added

2022-08-07 15:45 UTC, JulianGro requested changes
There is no replacements for interface/resources/qml/stylesUit/GraphikMedium.qml and similar.

2022-08-07 16:20 UTC, daleglass commented
Files added

2022-08-07 20:07 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-cf90061.sh
 - https://public.overte.org/build/overte/PR155/Overte-PR155-cf90061.tar.gz
 - https://public.overte.org/build/overte/PR155/Overte-PR155-cf90061.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-cf90061.exe

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-cf90061.dmg

2022-08-07 20:10 UTC, JulianGro requested changes

2022-08-07 20:10 UTC, JulianGro commented on interface/resources/qml/stylesUit/FiraSansRegular.qml
> +//  FiraSansMedium.qml
```suggestion
//  FiraSansRegular.qml
```
Not sure what is going on here

2022-08-07 20:10 UTC, JulianGro commented on interface/resources/qml/stylesUit/FiraSansSemiBold.qml
> +//  FiraSansMedium.qml
Not sure what is going on here
```suggestion
//  FiraSansSemiBold.qml
```

2022-08-07 22:31 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.sh
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.tar.Z
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.tar.gz
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.sh
 - https://public.overte.org/build/overte/PR155/Overte-PR155-7cd0422.tar.Z

2022-08-07 23:18 UTC, daleglass commented on interface/resources/qml/stylesUit/FiraSansSemiBold.qml
> +//  FiraSansMedium.qml
Copypasta

2022-08-08 01:41 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.sh
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.tar.gz
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.tar.Z
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.sh
 - https://public.overte.org/build/overte/PR155/Overte-PR155-d214384.tar.gz

2022-08-08 15:48 UTC, JulianGro approved these changes

2022-08-09 12:57 UTC, JulianGro commented
Just tested JSDOC with the font.
Everything is slightly smaller, but even making it only 5% bigger overshoots it, so I would just leave it as is.

2022-08-09 12:58 UTC, JulianGro commented
I don't see anything that needs testing other than JSDOC, since neither screenshare, nor the launcher or the simplified UI are in use or are planned to be used.

2022-08-12 11:31 UTC, ksuprynowicz commented
Can we merge this?

2022-08-12 11:36 UTC, merged