Feature/scripting isolation
overte-org/overte pull request #156
Opened 2022-08-08 15:19 UTC by ksuprynowicz

This it the scripting isolation PR by Heather that will be necessary for replacing QtScript with v8. It's amost ready except for problems with some vector instructions, with can take vector and scalar argument in any order according to documentaion, but with current implementation fail if order is reversed, which makes Create App and a lot of the scripts not work correctly.

2022-08-08 17:09 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-7f85a76.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-7f85a76.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-7f85a76.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-7f85a76.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-7f85a76.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-7f85a76.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-7f85a76.exe

2022-08-08 19:22 UTC, ksuprynowicz commented
To cause this issue try typing these lines in the scripting console:
```
print(JSON.stringify(Vec3.multiply({x: 1, y: 2, z: 3}, 1.5)));
print(JSON.stringify(Vec3.multiply(1.5, {x: 1, y: 2, z: 3})));
```
They should give the same result, and yet one of them returns NaN. I tried debugging is and it seems like float is getting cast to glm::vec3 (vector is {x: 1.5, y: 1.5, z: 1.5}), and float value becomes NaN for some reason which looks like a failed cast from vec3.
The second variant always gets called:
```
Vec3::multiply(const glm::vec3& v1, float f)
```

2022-08-11 00:27 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-565f2c3.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-565f2c3.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-565f2c3.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-565f2c3.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-565f2c3.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-565f2c3.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-565f2c3.exe

2022-08-11 15:14 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-e6080b7.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-e6080b7.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-e6080b7.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-e6080b7.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-e6080b7.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-e6080b7.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-e6080b7.exe

2022-08-12 00:31 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a01b3ad.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a01b3ad.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a01b3ad.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a01b3ad.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a01b3ad.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a01b3ad.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a01b3ad.exe

2022-08-12 02:56 UTC, AleziaKurdis commented
**Here's what I collected during my test (interface only)**
----
[7/11 21:31:7] [about:Entities 7] ERROR - [UncaughtException ScriptManager::run] 
Error: Cannot call native function PerformanceScriptingInterface::getPerformancePreset, 
its return value has not been registered with Qt in qrc:///serverless/Scripts/wizardLoader.js:29
[Backtrace]
    onWebAppEventReceived(sendingEntityID = '{325cd1c5-7935-4ea8-af9f-30f95f30bc70}', 
    event = '{"command":"first-run-wizard-ready"}') at qrc:///serverless/Scripts/wizardLoader.js:29
    <global>() at -1

**NOTE: Is it possible that it is because I used a clean installation? (It would be weird that it return an error instead of nothing)**  
    
---- 
[7/11 21:33:10] [about:Entities 7] ENTERING
[7/11 21:33:10] [about:Entities 7] ERROR - [UncaughtException {8b6c1b10-ba08-4b24-b4fb-b75b27f9b329}] 
Error: Function expected as argument to 'connect' in https://more.overte.org/tutorial/doppleganger.js?version=38851:229
[Backtrace]
    <anonymous>(options = [object Object]) at https://more.overte.org/tutorial/doppleganger.js?version=38851:229
    startDopplegangerShow(entityID = '{8b6c1b10-ba08-4b24-b4fb-b75b27f9b329}') 
    at qrc:///serverless/Scripts/activator-doppleganger.js:75
    <anonymous>(entityID = '{8b6c1b10-ba08-4b24-b4fb-b75b27f9b329}', ) 
    at qrc:///serverless/Scripts/activator-doppleganger.js:52
    <global>() at -1

**NOTE: connect / disconnect issue**  

----

[7/11 21:34:9] [about:Entities 7] LEAVING
[7/11 21:34:9] [about:Entities 7] ERROR - [UncaughtException {8b6c1b10-ba08-4b24-b4fb-b75b27f9b329}] 
Error: Function expected as argument to 'disconnect' in https://more.overte.org/tutorial/doppleganger.js?version=38851:258
[Backtrace]
    <anonymous>() at https://more.overte.org/tutorial/doppleganger.js?version=38851:258
    <anonymous>(entityID = '{8b6c1b10-ba08-4b24-b4fb-b75b27f9b329}', ) 
    at qrc:///serverless/Scripts/activator-doppleganger.js:58
    <global>() at -1

**NOTE: connect / disconnect issue**  

----    
[7/11 21:39:6] [app-doppleganger.js] INFO - Script Engine starting:app-doppleganger.js
[7/11 21:39:6] [app-doppleganger.js] ERROR - [UncaughtException evaluate] 
Error: Function expected as argument to 'connect' in https://more.overte.org/applications/doppelganger-mirror/app-doppleganger.js:40
[Backtrace]
    <global>() at https://more.overte.org/applications/doppelganger-mirror/app-doppleganger.js:40

**NOTE: connect / disconnect issue**  

----
**Not related, but seen during the test:**  

Default avatars are still on vircadia repo:
refreshed: https://cdn-1.vircadia.com/us-e-1/Bazaar/Avatars/Sean/fbx/Sean.fst?1660268439407

----
[7/11 21:52:42] [FloofChat.js] ERROR - [UncaughtException ScriptManager::run] 
Error: Result of expression 'AvatarManager.getPalData([sessionID]).data[0]' [undefined] is not an object. 
in file:///D:/Program Files/Overte - PR156/scripts/communityScripts/chat/FloofChat.js:668
[Backtrace]
    avatarLeavesDomain(sessionID = '{c4e46b63-e678-4dcf-9450-8d54678b630a}') 
    at file:///D:/Program Files/Overte - PR156/scripts/communityScripts/chat/FloofChat.js:668
    <global>() at -1

**Note: Hum... This seems to be a bug in the script.
The call is not protected against an empty array returned.
I don't have it with the current build, being alone.
but I have it with the new build (fresh install). and no display name set.
There is always a risk of an impact by the new script engine. To be checked.**

----    

[7/11 22:1:33] [about:Entities 12] ERROR - [UncaughtException {28adff02-41db-414a-9643-87d7a3715cca}] 
Error: Referencing deleted native object in http://metaverse.bashora.com/scripts/radio/radio_flight_tube.php?list=flight_tube_base_playlist:417
[Backtrace]
    <anonymous>(entityID = '{37fd51b4-08ef-4d7f-b58c-29f980d26917}', ) 
    at http://metaverse.bashora.com/scripts/radio/radio_flight_tube.php?list=flight_tube_base_playlist:417
    <native>(null) at -1
    ... more lines...
    <global>() at -1
[7/11 22:1:33] [about:Entities 12] INFO - Script Engine stopping:about:Entities 12

**NOTE: connect / disconnect issue**

----

2022-08-13 19:30 UTC, vegaslon commented
API Debugger appears to no longer work with this PR.

2022-08-14 21:43 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-32b1570.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-32b1570.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-32b1570.tar.Z

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-32b1570.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-32b1570.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-32b1570.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-32b1570.exe

2022-08-15 20:40 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2fc0c1c.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2fc0c1c.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2fc0c1c.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2fc0c1c.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2fc0c1c.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2fc0c1c.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2fc0c1c.exe

2022-08-15 23:39 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2a3b27b.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2a3b27b.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2a3b27b.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2a3b27b.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2a3b27b.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2a3b27b.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-2a3b27b.tar.gz

2022-08-17 10:48 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d98a8c5.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d98a8c5.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d98a8c5.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d98a8c5.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d98a8c5.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d98a8c5.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d98a8c5.exe

2022-08-17 18:51 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d407799.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d407799.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d407799.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d407799.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d407799.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d407799.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-d407799.exe

2022-08-18 12:51 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-fcd0d42.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-fcd0d42.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-fcd0d42.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-fcd0d42.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-fcd0d42.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-fcd0d42.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-fcd0d42.exe

2022-08-18 17:14 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6b6925c.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6b6925c.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6b6925c.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6b6925c.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6b6925c.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6b6925c.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6b6925c.exe

2022-08-19 14:13 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-b59ca77.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-b59ca77.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-b59ca77.sh

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-b59ca77.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-b59ca77.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-b59ca77.tar.Z

2022-08-19 15:33 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-1e6c15c.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-1e6c15c.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-1e6c15c.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-1e6c15c.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-1e6c15c.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-1e6c15c.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-1e6c15c.exe

2022-08-20 14:09 UTC, ksuprynowicz commented
I was not sure how to test API Debugger. Other than that everything seems to work now, so more testing and a code review would be very welcome :)

2022-08-20 14:17 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-eca3000.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-eca3000.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-eca3000.sh

2022-08-20 14:48 UTC, ksuprynowicz commented
I also tested domain server and assignment client scripts, both seem to work correctly.

2022-08-20 15:45 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a11c10c.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a11c10c.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a11c10c.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a11c10c.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a11c10c.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a11c10c.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-a11c10c.exe

2022-08-20 19:45 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.tar.Z
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.tar.gz
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.sh
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-476e5fb.exe

2022-08-21 17:35 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-4f7797c.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-4f7797c.exe

2022-08-21 17:52 UTC, vegaslon commented
This script does not apear to be working in this pr https://github.com/overte-org/overte-content/tree/master/Marketplace/gestureRose

2022-08-21 17:53 UTC, JulianGro commented
AppImage for testing is available here: https://data.moto9000.moe/overte_appimages/Overte-x86_64-PR156-7b39fe9.AppImage

2022-08-21 17:59 UTC, JulianGro commented
The Appreciate app that comes with Interface by default is broken.
Full log: https://bin.linux.pizza/?21bc5c9f4960e8fe#2kjqMKLBbB4nPYAyBQsqySgmrWoLraB2WsLrMZf1qQQj

2022-08-22 23:27 UTC, ksuprynowicz commented
Issue with Appreciate app is fixed now. I will check the issue @vegaslon posted tomorrow :)
At this point I don't expect any big changes in the code, so the PR is ready for review now.

2022-08-23 01:03 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-97cc4e7.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-97cc4e7.exe

2022-08-23 09:44 UTC, JulianGro commented
AppImage for testing: https://data.moto9000.moe/overte_appimages/Overte-x86_64-PR156-4a63a62.AppImage

2022-08-23 09:48 UTC, JulianGro commented
The Appricate apps dodecahedron is spawned in the wrong location.
Minor issue but needs to be looked at at some point.

2022-08-23 16:05 UTC, ksuprynowicz commented
I am not able to test rose gesture script, because it requires VR heaset and controllers and mine are not supported yet on Linux. @vegaslon Does it display any error message?

2022-08-23 16:07 UTC, ksuprynowicz commented
I get a warning:
`[08/23 18:06:07] [WARNING] [default] Model size of -1 is less than 0`
so I will investigate this part.

2022-08-23 16:56 UTC, vegaslon commented
[overte-log_2022-08-23_12.48.33_29c10a9f-da9d-4b9c-bf64-0c83c2fd796d.txt](https://github.com/overte-org/overte/files/9406364/overte-log_2022-08-23_12.48.33_29c10a9f-da9d-4b9c-bf64-0c83c2fd796d.txt)


hard to grab any relevent but this is filling up the logs now.

2022-08-23 18:35 UTC, Basinsky commented
I have tested a few of my scripts:
-puzzle: https://github.com/Basinsky/Puzzle/blob/main/puzzleSpawner.js -> is working
-timer: https://github.com/Basinsky/Timer/blob/main/TimesupSpawner.js -> is working
-Hearts card game: https://github.com/Basinsky/Hearts/blob/main/hearts-Spawner.js -> is working
-Murdergame: https://github.com/Basinsky/Murdergame/blob/master/MurderGameSpawner.js -> is working
-Fly game: https://github.com/Basinsky/FlyGame/blob/main/FlyGameSpawner.js -> is working

so far they all seem to work.

2022-08-23 18:40 UTC, Basinsky commented
I have noticed when I run two instances of interface and both the avatars are woodies, when I reload content on one interface, one of the woodies does not have any textures. I dont know if its releated to this PR 
![image](https://user-images.githubusercontent.com/51274563/186237832-13d84ffa-ccee-454e-9fab-77293c2e55f7.png)

2022-08-23 18:44 UTC, Basinsky commented
This is when I reload content the second time:
![image](https://user-images.githubusercontent.com/51274563/186238705-ac027804-ffa7-4390-82e1-655f90d696ec.png)

2022-08-23 19:59 UTC, ksuprynowicz commented
@vegaslon I was not able to replicate problem with log messages. It seems that it might be caused by some additional app I don't have. I've seen some error messages but not `cannot set property Accessible.pressed`. I tested rose script in VR on Windows and got following error message, although I'm not sure if it's related to the script, because these functions are not used in it:
```
[08/23 19:05:40] [DEBUG] [hifi.shared] Warning -- getAngularVelocity failed QUuid("{aaa56ba0-7925-493d-90af-20b0c5493f6a}")
[08/23 19:05:40] [DEBUG] [hifi.shared] Warning -- getWorldVelocity failed QUuid("{aaa56ba0-7925-493d-90af-20b0c5493f6a}")
```
I think that problem with the rose script is similar to the problem with appreciation dodecadehron appearing in wrong place in Appreciate app, because they use very similar functions. I will try to figure that one first and see if it fixes rose app too.

2022-08-23 20:13 UTC, vegaslon commented
that is interesting I am receiving these error messages on two different computers, running only default apps on both.

2022-08-23 20:20 UTC, ksuprynowicz commented
@vegaslon Are you running the newest build of this PR?
https://public.overte.org/build/overte/PR156/Overte-PR156-97cc4e7.exe

2022-08-23 20:24 UTC, vegaslon commented
I am indeed running the latest build. On windows I have been able to make it sprout this error message by simply focusing the log window.

2022-08-23 20:44 UTC, ksuprynowicz commented
I didn't notice this on Windows either, but I'm not sure if I focused log window. I will try next time I boot Windows.
I will also look into fixing the API debugger if possible.

2022-08-24 17:18 UTC, ksuprynowicz commented
Here's the simplest possible code replicating problem with API Debugger (any other global object can be used, not just MyAvatar):
`JSON.stringify(Object.keys(MyAvatar))`
It should return list of objects and properties, but returns nothing.
I also found the cause of problems with dodecahedron position in appreciate app, and rose app not working. It turns out that this is caused by `MyAvatar.getJointPosition(joint_index)` returning position of entire avatar and not given joint.
I think that we can fix API Debugger later, but `MyAvatar.getJointPosition` needs to work correctly.
As always help in fixing both issues is very welcome.

2022-08-24 18:03 UTC, ksuprynowicz commented
It seems that function overloading is again causing trouble. For example for `JSON.stringify(MyAvatar.getJointPosition("Hips"))` function using integer is called instead, although this problem is unrelated to Appreciate app, because it gets indices and uses them with `getJointPosition`. The weirdest part is that `getJointPosition` with index number works well in scripting console.

2022-08-24 18:13 UTC, ksuprynowicz commented
I misread the program. Appreciate app uses joint name string argument in getJointPosition so this should be pretty easy to fix.

2022-08-24 22:32 UTC, ksuprynowicz commented
@vegaslon The [gestureRose](https://github.com/overte-org/overte-content/tree/master/Marketplace/gestureRose) script should work now, and all the other scripts that use MyAvatar.getJointPosition should work too :)

2022-08-24 22:41 UTC, ksuprynowicz commented
It's pretty much ready for review now. I don't think any big changes will happen.

2022-08-24 23:52 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-6c88d1b.dmg

2022-08-25 06:33 UTC, JulianGro commented
AppImage for testing: https://data.moto9000.moe/overte_appimages/Overte-x86_64-PR156-8df0f2d.AppImage

2022-08-25 21:58 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-116cd8f.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-116cd8f.exe

2022-08-27 21:58 UTC, HifiExperiments requested changes

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptEngineCast.h
> +int scriptRegisterMetaTypeWithLambdas(ScriptEngine* eng,
delete if unused?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptEngines.cpp
> +    manager->waitTillDoneRunning();
👍 

just to confirm, since we're had lots of issues with script shutdowns in the past, do the managers actually finish running, and we get past this line?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptManager.cpp
> +    while (here != nullptr) {
interesting!  does the order ever matter here?  like when we register a type and then register a vector of that type?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptManager.cpp
> -    state->setObjectName("ResourceState");
does this object name matter?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptManager.cpp
> +    scriptRegisterMetaType<MeshProxyList, meshesToScriptValue, meshesFromScriptValue>(scriptEngine);
since we have the cool static initializer, could all of these be moved into their respective libraries/classes?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptManager.h
> +    Q_INVOKABLE void clearInterval(QVariantMap timer) { ; }
could you explain what this does?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptValueUtils.cpp
> +    scriptRegisterMetaType<std::shared_ptr< MiniPromise >, promiseToScriptValue, promiseFromScriptValue>(engine);
wasn't this already registered in an earlier file?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptEngineQtScript_cast.cpp
> +    return 0;
I think we need some comments/constants to explain the different values.

some dumb questions: does this only matter for built in meta types?  what about like enums <-> int?  will all of these conversion checks affect perf at all?

and as a more general question, could we maybe document the process of how to add a new exposed type in the future somwhere?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptEngineQtScript_cast.cpp
> +    }*/
delete

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +                ;
```suggestion
                break;
```

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +                    printf("Method with QMetaType::UnknownType");
remove printf and commented out qDebug above

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +    isMetaRejected.resize(num_metas);
do we need to preallocate all of these?  seems expensive?  is this called every time we call from js to c++?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +        qGenArgsVectors[i].resize(10);
why 10?  is that an argument limit?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +        if (isValidMetaSelected && !isMetaRejected[i] && conversionPenaltyScore[bestMeta] > conversionPenaltyScore[i]) {
could we save `conversionPenaltyScore[bestMeta]` in a temp variable so we don't have to compute it every loop, only when we get a new bestMeta?

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +            conn.callback.call(conn.thisValue, args);
```suggestion
        conn.callback.call(conn.thisValue, args);
```

2022-08-27 21:58 UTC, HifiExperiments commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +    withReadLock([&]{
there's `resultWithReadLock` for this

2022-08-28 11:51 UTC, ksuprynowicz commented on interface/src/avatar/MyAvatar.cpp
> +    DependencyManager::get<AvatarManager>()->getMyAvatar()->registerProperties(scriptEngine);
Good point. AvatarManager singleton created in `setupEssentials` and that's when `_myAvatar` is created too. While there's null check in `DependencyManager::get<AvatarManager>()`, it only displays a warning, but `getMyAvatar()` would still be accessed causing a segfault. I will fix it in next commit :)

2022-08-28 12:23 UTC, ksuprynowicz commented on interface/src/Application.cpp
> +    pickScriptingInterface->registerProperties(scriptEngine.get());
Good idea. It will be tidier this way.

2022-08-28 12:32 UTC, ksuprynowicz commented on interface/src/scripting/RenderScriptingInterface.cpp
> +    scriptEngine->registerEnum("AntialiasingMode",QMetaEnum::fromType<AntialiasingConfig::Mode>());
It's becuse we don't have a parent object for antialiasing enum. Enum definition belongs to a class that is not exposed to scripting engine.

2022-08-28 12:34 UTC, ksuprynowicz commented on interface/src/ui/InteractiveWindow.cpp
> +    auto scriptEngine = manager->engine().get();
It's Heather's code that I copied from `STATIC_SCRIPT_INITIALIZER`. I think it's to make them more future-proof. We might need to do something with script manager in them in the future.

2022-08-28 12:39 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptEngines.cpp
> +    manager->waitTillDoneRunning();
I had a lot of problems with script engine thread crashing due to script engine being deleted too early. I'm pretty sure I've seen such crashes in older versions too - it can be recognized by `this` object wirth corrupted data when debugging the crash.

2022-08-28 12:43 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManager.cpp
> +    while (here != nullptr) {
The order doesn't matter, because vector of given type is condidered as completely different meta type by Qt's meta object system. The only thing that matters is that types should be registered before properties of given type get registered. Otherwise we get properties with unknown meta type and it can't be fixed later.

2022-08-28 12:54 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManager.cpp
> -    state->setObjectName("ResourceState");
It does, but ResourceState was not working correctly with current implementation, probably because it needs to be the same as in meta type. I registered it as `State`, so it's available as `Resource.State`.

2022-08-28 13:05 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManager.cpp
> +    scriptRegisterMetaType<MeshProxyList, meshesToScriptValue, meshesFromScriptValue>(scriptEngine);
Good idea - it will be a lot tidier this way. I will move them in the next commit.

2022-08-28 13:07 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManager.cpp
> +    while (here != nullptr) {
After thinking a bit more about it, it seems that order might matter if vector of given type is registered with scriptRegisterSequenceMetaType.

2022-08-28 14:05 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManager.h
> +    Q_INVOKABLE void clearInterval(QVariantMap timer) { ; }
It's necessary, because one shot timers automatically get deleted after timer fires. Then script value converts to QVariantMap instead of QTimer*. Normally it would cause attribute conversion error, so we need an overloaded operator to handle this. Since timer is deleted it doesn't actually need to do anything.

2022-08-28 14:26 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptEngineQtScript_cast.cpp
> +    return 0;
Comments are a good idea - without them it's kinda confusing. I commented each case.
Sadly there's no way to do this for enums, because they are just treated as numbers on JS side. We could iterate through custom enum types, but that would increase computation cost a lot. I think that the best way would be avoiding overloading functions with different enum types.
The currrent checks shouldn't affect performance almost at all for non-overloaded functions, and for overloaded functions there's pretty much no other way to determine which function to call. This results from JS having no concept of function overloading.
As for documenting adding new types and global objects, what would be the best place to add it?

2022-08-28 14:40 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +    isMetaRejected.resize(num_metas);
When exposing functions through QtMetaMethods it is necessary. It shouldn't be too expensive, because it's just empty QVectors that are created on this step, and for most functions `num_metas == 1`. For overloaded functions the cost starts to increase so it would be good to avoid situations where there's a lot of overloaded function that are called often. The alternative to this in V8 would be adding custom converter inside each function so the benefit wouldn't be significant, and would mean repeating a lot of code.

2022-08-28 14:42 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +        qGenArgsVectors[i].resize(10);
I agree that it's really silly but it's how Qt does it for some reason:
https://doc.qt.io/qt-5/qmetamethod.html#invoke-1

2022-08-28 14:53 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +        if (isValidMetaSelected && !isMetaRejected[i] && conversionPenaltyScore[bestMeta] > conversionPenaltyScore[i]) {
It's stored in array so it's not computed, but you have a point - I was able to simplify code, get rid of entire loop and several QVectors this way.

2022-08-28 15:09 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +    withReadLock([&]{
Thanks! This could be really difficult to debug later. I also limited lifetime of resulting value so connection list doesn't stay locked too long.

2022-08-28 16:31 UTC, ksuprynowicz commented on interface/src/scripting/PerformanceScriptingInterface.cpp
> +        //qRegisterMetaType<PerformanceScriptingInterface::RefreshRateProfile>("PerformanceScriptingInterface::RefreshRateProfile");
Fixed :)

2022-08-28 16:36 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptValueUtils.cpp
> +    scriptRegisterMetaType<std::shared_ptr< MiniPromise >, promiseToScriptValue, promiseFromScriptValue>(engine);
True, thanks!

2022-08-28 16:36 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptEngineQtScript_cast.cpp
> +    }*/
Done!

2022-08-28 16:40 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +    withReadLock([&]{
I'm a bit stuck on this one. When I use resultWithReadLock, every app stops working, and reloading scripts causes a crash. I think I'm using resultWithReadLock incorrectly, or misunderstanding it:
```
ScriptSignalQtProxy::ConnectionList::iterator ScriptSignalQtProxy::findConnection(QScriptValue thisObject, QScriptValue callback) {
    ConnectionList::iterator iter;
    resultWithReadLock<ScriptSignalQtProxy::ConnectionList::iterator>([&]{
        for (iter = _connections.begin(); iter != _connections.end(); ++iter) {
            Connection& conn = *iter;
            if (conn.callback.strictlyEquals(callback) && conn.thisValue.strictlyEquals(thisObject)) {
                break;
            }
        }
        return iter;
    });
}
```

2022-08-28 17:34 UTC, ksuprynowicz commented on libraries/script-engine/src/qtscript/ScriptObjectQtProxy.cpp
> +    withReadLock([&]{
I think I figured it out. I sent a commit with updated version. Let me know if it's ok :)

2022-08-28 18:15 UTC, daleglass commented
Tiny nitpick: tests/animation/CMakeLists.txt now needs adding a dependency on script-engine

2022-08-28 18:18 UTC, ksuprynowicz commented
> Tiny nitpick: tests/animation/CMakeLists.txt now needs adding a dependency on script-engine

Would the line look like this?
`link_hifi_libraries(shared animation gpu hfm model-serializers graphics networking script-engine test-utils image)`

2022-08-28 18:18 UTC, daleglass commented
Yup!

2022-08-28 18:20 UTC, ksuprynowicz commented
Thanks! I will send a fix together with create app fix if I figure it out today.

2022-08-28 23:31 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-55c382a.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR156/Overte-PR156-55c382a.exe

2022-08-29 01:21 UTC, vegaslon commented
The equip functionality of the interface also appears to not be working with this PR. Here is a test script for you to rez a equiptable object. https://raw.githubusercontent.com/overte-org/overte/17b483284d98edbcf715651cea7b7c471dd363cf/unpublishedScripts/parent-ator/createParentator.js
When this object is out in the open when you click on it it should attach to your hand in both VR mode and Desktop mode. To unattach in desktop mode you hit the U key. Equip functions are accessed though the use of the Userdata field which is used by the default controller scripts, especially this one https://github.com/overte-org/overte/blob/17b483284d98edbcf715651cea7b7c471dd363cf/scripts/system/controllers/controllerModules/equipEntity.js

2022-08-29 02:04 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptEngines.cpp
> +    manager->waitTillDoneRunning();
yeah totally, I think this is a great find!  I just want to make sure it’s doing what we expect.  I also wonder if this is what’s causing the long pauses when using create, if it’s happening on the main thread.

2022-08-30 23:15 UTC, daleglass requested changes
Not a full review, just things I came across while reading the code.

2022-08-30 23:15 UTC, daleglass commented on libraries/script-engine/src/ScriptManager.cpp
> +    while (!_isFinished) {
I can't find a place where _isFinished changes

2022-08-30 23:15 UTC, daleglass commented on libraries/script-engine/src/ScriptManager.cpp
> +        _engine->evaluate(_scriptContents, _fileNameString);
evaluate returns a return value, which allows obtaining the return value of the script.

I'll be adding code to capture this because it'll assist with testing.

2022-09-02 18:07 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManager.cpp
> +    while (!_isFinished) {
It's changed in `libraries/script-engine/src/ScriptManager.cpp`, line 1042.

2022-09-02 21:47 UTC, SilverfishVR commented
Reloading any script (from "running scripts") seems to cause a lot of critical errors not related to the script being reloaded:

```
[09/02 23:31:38] [WARNING] [hifi.scriptengine] ScriptManager::waitTillDoneRunning called, but the script is on the same thread: "app-more.js"
[09/02 23:31:38] [DEBUG] [hifi.scriptengine] AssetScriptingInterface::AssetScriptingInterface ScriptManager(0x2c6b07b19e0)
[09/02 23:31:38] [DEBUG] [hifi.scriptengine] loadURL "file:///C:/Program Files/Overte - PR156/scripts/system/more/app-more.js" "Success" QThread(0x2c62746d0c0, name = "Main Thread")
[09/02 23:31:38] [CRITICAL] [default] Method  PlatformInfoScriptingInterface :: "getInstance"  has QMetaType::UnknownType return value
[09/02 23:31:38] [CRITICAL] [default] Method  AvatarManager :: "findParabolaIntersectionVector"  has QMetaType::UnknownType return value
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  AvatarManager :: "findParabolaIntersectionVector"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  2 in method  DesktopScriptingInterface :: "createWindowOnThread"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  TabletScriptingInterface :: "playSound"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  Stats_QML_270 :: "_q_createJSWrapper"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  Stats_QML_270 :: "mapFromItem"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  Stats_QML_270 :: "mapToItem"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  Stats_QML_270 :: "mapFromGlobal"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  Stats_QML_270 :: "mapToGlobal"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  Stats_QML_270 :: "forceActiveFocus"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Method  ControllerScriptingInterface :: "getAllActions"  has QMetaType::UnknownType return value
[09/02 23:31:38] [CRITICAL] [default] Method  ControllerScriptingInterface :: "getAvailableInputs"  has QMetaType::UnknownType return value
[09/02 23:31:38] [CRITICAL] [default] Parameter  2 in method  ControllerScriptingInterface :: "triggerHapticPulse"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  1 in method  ControllerScriptingInterface :: "triggerShortHapticPulse"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  3 in method  ControllerScriptingInterface :: "triggerHapticPulseOnDevice"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  2 in method  ControllerScriptingInterface :: "triggerShortHapticPulseOnDevice"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  1 in method  AddressManager :: "goToLocalSandbox"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  AddressManager :: "goToEntry"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  scripting::Audio :: "setReverbOptions"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  MyAvatar :: "setRawJointData"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  MyAvatar :: "sanitizeAvatarEntityProperties"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  MyAvatar :: "getRawDriveKey"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  MyAvatar :: "disableDriveKey"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  MyAvatar :: "enableDriveKey"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  MyAvatar :: "isDriveKeyDisabled"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  1 in method  ScriptManager :: "executeOnScriptThread"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  DebugDraw :: "drawRays"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  DebugDraw :: "drawRays"  is of type QMetaType::UnknownType
[09/02 23:31:38] [CRITICAL] [default] Parameter  0 in method  DebugDraw :: "drawRays"  is of type QMetaType::UnknownType
```

The first warning seems interesting:

`[WARNING] [hifi.scriptengine] ScriptManager::waitTillDoneRunning called, but the script is on the same thread`

2022-09-02 21:52 UTC, ksuprynowicz commented
Thanks! I added that critical error message to identify functions that might possibly not work and probably need testing.

2023-05-01 16:13 UTC, closed without merging