Update VCPKG
overte-org/overte pull request #162
Opened 2022-08-13 16:31 UTC by JulianGro

This PR updates VCPKG for Windows amd64, Linux amd64, Linux aarch64, and macOS amd64.

2022-08-13 20:43 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-bb58e71.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-bb58e71.exe

2022-08-14 13:54 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-4600443.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-4600443.exe

2022-08-15 22:42 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.tar.gz
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.sh
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.sh
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.tar.Z
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR162/Overte-PR162-a6ac375.exe

2022-08-21 16:32 UTC, ksuprynowicz requested changes
I'm really worried about Bullet physics changes. Earlier by default neither Release nor RelWithDebInfo was set, making it extremely slow (up to 22 times from my tests). We will also need to test how this affects Opus performance.

2022-08-21 16:32 UTC, ksuprynowicz commented on cmake/ports/bullet3/portfile.cmake
> -message("Optimization options for Bullet: ${VIRCADIA_BULLET_OPTIONS}")
Won't this mean that Bullet will be again built entirely unoptimized on Linux and without architecture-specific flags?

2022-08-21 16:32 UTC, ksuprynowicz commented on cmake/ports/opus/portfile.cmake
> +  master
Same thing as with Bullet.

2022-08-21 16:33 UTC, ksuprynowicz commented
I will build it on Linux and test the perfromance soon.

2022-08-21 17:12 UTC, JulianGro commented on cmake/ports/bullet3/portfile.cmake
> -message("Optimization options for Bullet: ${VIRCADIA_BULLET_OPTIONS}")
VCPKG sets those flags automatically, so there shouldn't be any difference.

2022-08-21 17:12 UTC, JulianGro commented on cmake/ports/opus/portfile.cmake
> +  master
VCPKG sets those flags automatically, so there shouldn't be any difference.

2022-08-21 19:30 UTC, ksuprynowicz commented on cmake/ports/bullet3/portfile.cmake
> -message("Optimization options for Bullet: ${VIRCADIA_BULLET_OPTIONS}")
There doesn't seem to be any difference on the Bullet performance. I will also test Opus soon.

2022-08-21 19:36 UTC, ksuprynowicz commented on cmake/ports/opus/portfile.cmake
> +  master
Opus performance is fine too. I think this PR is safe to merge.

2022-08-21 20:28 UTC, JulianGro commented on cmake/ports/opus/portfile.cmake
> +  master
Give me an "Approved" and a "CR approved" then ;)

2022-08-21 20:30 UTC, merged