Add Docker based server packaging
overte-org/overte pull request #174
Opened 2022-08-24 14:11 UTC by JulianGro

This PR adds Dockerfiles and instructions for building server packages for Debian 11, Ubuntu 18.04, Ubuntu 20.04, Ubuntu 22.04, and Fedora 36.
Rocky Linux 9 packaging is unfinished.
It also adds Dockerfiles and instructions for initial Docker images. This is not properly tested however, and probably needs more work.

Example packages are available here:
https://data.moto9000.moe/m/temp/overte-server-1.experimental-1.fc36.x86_64.rpm
https://data.moto9000.moe/m/temp/overte-server_0.1-experimental-debian-11-1_amd64.deb
https://data.moto9000.moe/m/temp/overte-server_1-experimental-ubuntu-18.04-1_amd64.deb
https://data.moto9000.moe/m/temp/overte-server_1-experimental-ubuntu-20.04-1_amd64.deb
https://data.moto9000.moe/m/temp/overte-server_1-experimental-ubuntu-22.04-1_amd64.deb
Keep in mind that these packages weren't all build on the same source version.

2022-08-24 16:21 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR174/Overte-PR174-2238395.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR174/Overte-PR174-2238395.exe

2022-08-24 21:45 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR174/Overte-PR174-9dfa3d1.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR174/Overte-PR174-9dfa3d1.exe

2022-09-07 16:34 UTC, ksuprynowicz requested changes
Everything looks fine to me. I have questions about a few details though.

2022-09-07 16:34 UTC, ksuprynowicz commented on pkg-scripts/overte-assignment-client.service
> +ExecStart=/opt/overte/assignment-client --min 6 --max 20
Won't "max 20" interfere with audio thread setting in server's web UI? Or these are separate things and multiple audio mixer threads count as single assignment client?

2022-09-08 18:47 UTC, JulianGro commented on pkg-scripts/overte-assignment-client.service
> +ExecStart=/opt/overte/assignment-client --min 6 --max 20
The domain server will only rez as many assignment clients as it needs.
Why this code was added in the first place, I don't know. Maybe just future proofing in case we add more assignment clients.
But in reality, there should never be more than 6 assignment clients per domain server.

2022-09-08 18:48 UTC, JulianGro commented on INSTALLER.md
> +VIRCADIA_USE_SYSTEM_QT=true cmake .. -DVIRCADIA_CPU_ARCHITECTURE=-msse3 -DVCPKG_BUILD_TYPE=release -DSERVER_ONLY=true -DBUILD_TOOLS=true
I think it should just be replaced in the last PR to be merged of the two.

2022-09-08 18:52 UTC, JulianGro commented on INSTALLER.md
> +1. Build Docker image as instructed in the relevant Dockerfile in [tools/ci-scripts/deb_package/](tools/ci-scripts/rpm_package/)
Good catch.

2022-09-08 19:02 UTC, ksuprynowicz commented
Can we merge it? I'd then rebase PR 149 on it and make release candidate build.

2022-09-08 19:10 UTC, JulianGro commented
Sure

2022-09-08 19:19 UTC, merged

2022-09-08 19:19 UTC, ksuprynowicz commented
Thanks!

2022-09-08 20:58 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR174/Overte-PR174-b16ab1c.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR174/Overte-PR174-b16ab1c.exe