V8 scripting engine
overte-org/overte pull request #185
Opened 2022-09-02 22:45 UTC by ksuprynowicz

Very early work in progress. Just added V8 vcpkg for now.

2023-03-11 22:50 UTC, JulianGro commented on libraries/shared/src/shared/WebRTC.h
> -#  define WEBRTC_AUDIO 1
Marking this so we don't forget to reenable webrtc.

2023-05-13 12:36 UTC, daleglass commented
Excellent work, thanks a lot for this!

Okay, so this is a tough one to review, so I think it'll take some time. But we can do it bit by bit, and we can start with the easy stuff first.

# V8TODO

There's 205 instances of "V8TODO" in this code. I think that should be trimmed down.

1. Are all of those current? There may be some that don't apply anymore.
2. Are there any that need fixing before this is usable?
3. Which are things that would be nice to have long term, but which aren't essential? Eg, performance improvements.

# Documentation

Code could use more Doxygen. This is excellent work but very hard for a new person to get into. We could use documentation on:

1. The overall structure. Where do things start, what are the main concepts, what's the execution flow for a running script.
2. Documenting the actual classes and methods.

2023-05-13 12:57 UTC, ksuprynowicz commented
Hi!

> Are all of those current? There may be some that don't apply anymore.

I went though these recently, and they are mostly current. A lot of them are pretty much impossible to figure out due to lack of documentation, but would provide good clues for debugging if something goes wrong. I will go through them again after we do more testing.

> Are there any that need fixing before this is usable?

Right now V8 branch is not only usable but also better than QtScript one in most aspects. It mostly needs testing and bugfixing.

> Documenting the actual classes and methods.

Since most of V8 classes inherit from base abstract classes, would it be ok for methods that are overridden to be documented just on the base class?

2023-05-13 23:51 UTC, daleglass requested changes
Okay, very, very preliminary review based on just reading through the code from top to bottom.

Some of the things I need to look into further.

2023-05-13 23:51 UTC, daleglass commented on libraries/shared/src/SettingHelpers.cpp
> +            // QML has problems with QVariant::Hash
What problems?

2023-05-13 23:51 UTC, daleglass commented on libraries/shared/src/shared/QtHelpers.cpp
> +QString isBlockingForbiddenThread(QThread* currentThread) {
What is this for, and what does it return?

2023-05-14 00:15 UTC, gydence commented on assignment-client/CMakeLists.txt
> -setup_hifi_project(Core Gui Network Script Quick WebSockets)
this is different than link_hifi_libraries

2023-05-14 01:03 UTC, gydence reviewed
idk how much I’ll get a chance to review but taking a look

2023-05-14 01:03 UTC, gydence commented on interface/src/LoginStateManager.cpp
> +        {"pathPropertyIndex", halfPathRenderStateIndex},
still reading but this “index” method seems a little dangerous/liable to confuse folks?

2023-05-14 06:17 UTC, JulianGro commented on .github/workflows/pr_build.yml
> +              apt-dependencies: libnode-dev
If you remove this commit and rebase, this line can be dropped. I think Ubuntu 22.04 comes with the wrong libnode version, so we I will need to prebuild for VCPKG (which was needed anyways).

2023-05-14 18:28 UTC, daleglass commented on assignment-client/CMakeLists.txt
> -setup_hifi_project(Core Gui Network Script Quick WebSockets)
Doh! Okay, brain fart here.

2023-05-14 20:02 UTC, ksuprynowicz commented on libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
> +                    return true;
It's confusing for me too, we should take a look together

2023-05-14 20:10 UTC, ksuprynowicz commented on libraries/script-engine/src/MenuItemProperties.cpp
> +    return true;
Functions that convert from script value to C++ objects return boolean that shows if conversion was successful. We could do some extra checks and return false when script value is not an object. What do you think?

2023-05-14 20:25 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManager.cpp
> +    // SANITY/PERFORMANCE CHECK USING SANDBOX
Thanks! That's why script whitelist didn't work. On the other hand I'm not sure about usefulness of sandboxed entity script test, and I'm not sure how to make it work on V8. I will try to get the witelist runnign and experiment a bit with sandbox.

2023-05-14 20:26 UTC, ksuprynowicz commented on libraries/shared/src/SettingHelpers.cpp
> +            // QML has problems with QVariant::Hash
It doesn't seem to be able to convert QVariant::Hash into a script value or from script value to QVariant::Hash.

2023-05-14 20:32 UTC, ksuprynowicz commented on libraries/shared/src/shared/QtHelpers.cpp
> +QString isBlockingForbiddenThread(QThread* currentThread) {
In practice it protects against invoking methods with Qt::BlockingQueuedConnection on render thread (that's the only thread that's forbidden at the moment). Maybe to avoid stutters?

2023-05-14 20:52 UTC, ksuprynowicz commented on interface/CMakeLists.txt
> +include_hifi_library_headers(script-engine)
It looks like instead it's likned to libraries that depend on it and these are linked to Interface. Application.cpp does directly depend on script engine, so how do you think, should we add it here too for clarity?

2023-05-14 21:17 UTC, ksuprynowicz commented on interface/src/RefreshRateManager.h
> +    UXMode _uxMode { UXMode::UX_NUM };
Thanks! I corrected it in cleanup.

2023-05-14 21:27 UTC, ksuprynowicz commented on interface/src/LoginStateManager.cpp
> +        {"pathPropertyIndex", halfPathRenderStateIndex},
Agreed. My intention here was to make it easy to use from script engine side. There `pathPropertyIndex` and all entity properties objects are automatically generated by `rayPointerPropertiesFromScriptValue`. From C++ side it's done in such way because for automatic conversion it would need to have access to script engine - QVariantMap cannot be converted directly into entity properties without one.

2023-05-14 21:30 UTC, ksuprynowicz commented on .github/workflows/pr_build.yml
> +              apt-dependencies: libnode-dev
I think I removed it during rebase

2023-05-15 20:43 UTC, ksuprynowicz commented on libraries/script-engine/src/MenuItemProperties.cpp
> +    return true;
Thanks! Fixed :)

2023-05-15 21:03 UTC, daleglass commented on libraries/shared/src/shared/QtHelpers.cpp
> +QString isBlockingForbiddenThread(QThread* currentThread) {
I'm still not sure I really like this existing at all, so I'll have to get back to this later and try to figure out whether this is really necessary. Just seems very hacky to me.

But it doesn't appear to be urgent for the time being.

2023-05-15 21:27 UTC, ksuprynowicz commented on libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
> +                    return true;
Fixed!

2023-05-15 22:00 UTC, ksuprynowicz commented on interface/src/LoginStateManager.cpp
> +
Thanks!

2023-05-27 20:22 UTC, merged