Re-coded to be more stable.
overte-org/overte pull request #190
Opened 2022-09-15 03:12 UTC by AleziaKurdis

This is a an almost complete re-coding of the notifications script. The previous version had too useless complexities and was computing each element position independently causing the notifications to be unstably displayed in HMD if the user moved. There was also too many array used to achieved this. It was a bit painful.

This new version use an invisible entity parented to the avatar as a "container" where the notification elements are parented to it, making the positioning easier and more stable if the avatar moves. I used only one array of objects to contain the the notification stack. There is also a better management of some signal to avoid useless computing when it wasn't necessary. I think the code is also more clear.

I got rid of the little x buttons to close the notification, it was on each element, you had to target a very small square surface with the mouse if you wanted to absolutely close a notification within the 10 second of their existence. Now you can close a notification simply by clicking on it (on all its surface) But as before, the close function works only on desktop mode. (Apparently it's relatively complex to get the id of the entity that you click on in HMD. Maybe one day.)

It's also easier now to adjust the scale of the notifications in HMD if we want too, (only one value to change in the script) The parenting using a container entity has also made all the notification UI in HMD scaling correctly according the avatar scale (it was free by parenting all those together).

2022-09-15 05:20 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR190/Overte-PR190-5b81a41.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR190/Overte-PR190-5b81a41.exe

2022-09-17 02:52 UTC, AleziaKurdis commented
Added a new way to dismis the notification in HMD:
https://youtu.be/3tnzHXVu2H4

2022-09-17 04:39 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR190/Overte-PR190-ade4bd7.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR190/Overte-PR190-ade4bd7.exe

2022-09-17 15:34 UTC, ksuprynowicz requested changes
Everything looks ok to me, but I'm wondering if the comment at the top explaining how to add new notifications could be updated instead of being removed. It could be useful when someone adds new notificatons.

2022-09-17 15:34 UTC, ksuprynowicz commented on scripts/system/notifications.js
> -//  }
Maybe this comment could be updated instead of being removed?

2022-09-17 15:50 UTC, AleziaKurdis commented on scripts/system/notifications.js
> -//  }
I will review it again.
It looked like the original work document. Some stuff in that wasn't implemented or have been implemented separatly.
I will see if there still something valuable in that.

2022-09-17 16:02 UTC, ksuprynowicz commented on scripts/system/notifications.js
> -//  }
Thanks! If the original was outdated/not implemented then it's perfectly fine to remove it in my opinion.

2022-09-18 02:36 UTC, AleziaKurdis commented
I reviewed the comment that was present in the original script. 
There was a part about notifying on a key press event. I think it was a wrong approach. Normally it's an action that call a notification. Not from the hotkeys directly.  
There are many way to call a notification and it's already supported by this script. (One of them is: https://apidocs.overte.org/Window.html#.displayAnnouncement )
Added a new notification event is no rocket science. There is like 11 examples of this in that script.

I'm more concerned now by the potential of annoyance that this functionality can do if a grieffer discovers that it can be used relatively easilly. 
Mainly using this: https://apidocs.overte.org/Messages.html#.sendMessage (with localOnly set to false)
But this was already like this since 2014.
(Note that people can also just play "banana phone" in loop in their microphone to be even more annoying, so...)
I guess it's why we wanted a whitelist... (a feature that will need to be revisited cause it doesn't make sense to block the script from the domain it-self)

2022-09-18 04:26 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR190/Overte-PR190-3481217.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR190/Overte-PR190-3481217.exe

2022-10-15 21:28 UTC, AleziaKurdis commented
I lived with this new version of "notificatification.js" for a month now. No issues so far.

2022-10-15 21:30 UTC, ksuprynowicz commented
Thanks!

2022-10-15 21:30 UTC, merged