Fixed create app entity intersections in VR, increased default voxel resolution
overte-org/overte pull request #191
Opened 2022-09-15 18:54 UTC by ksuprynowicz

2022-09-15 18:57 UTC, ksuprynowicz commented
This fixes annoying bug with unexpectedly selecting entities in VR when moving entity with handle that is obsucred by another object and bug with voxeld being edited when clicking on tablet. Defalut voxel resolution is also increased to higher value.

2022-09-17 15:37 UTC, ksuprynowicz commented
Anyone would like to review this? It fixes bugs that made create app almost unusable in VR in earlier versions so I would like to include it in the upcoming release.

2022-09-17 17:53 UTC, ksuprynowicz commented
I tested it on Windows in VR and everything seems to work well. It didn't break anything in Desktop mode on Linux either.

2022-09-18 19:18 UTC, daleglass requested changes

2022-09-18 19:18 UTC, daleglass commented on scripts/system/controllers/controllerModules/inEditMode.js
> +                            print("selectEntity message")
Probably could use the wantDebug check

2022-09-18 19:18 UTC, daleglass commented on scripts/system/controllers/controllerModules/inEditMode.js
> +                            print("selectOverlay message")
here too

2022-09-18 20:16 UTC, merged

2022-09-18 22:25 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR191/Overte-PR191-d572fb3.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR191/Overte-PR191-d572fb3.exe