Tell accountmanager url changed
overte-org/overte pull request #2
Opened 2022-01-18 20:46 UTC by ksuprynowicz

Branch mabe by Frost, that will allow live switching of current metaverse server. Currently in this branch switching servers requires restart of the interface, so more work is needed.

2022-01-22 15:28 UTC, ksuprynowicz commented
When changing metaverse server, account manager setAuthURL method apparently fails to be called:
`[01/22 16:24:42] [WARNING] [default] qrc:/qml/LoginDialog/LinkAccountBody.qml:410: ReferenceError: setAuthURL is not defined`
I think this is the reason that live switching fails.

2022-01-22 18:37 UTC, ksuprynowicz commented
I tested it on Linux an it seems to work well now. I need a code review :)

2022-01-24 21:39 UTC, ksuprynowicz commented
It's tested on Windows now too.

2022-01-27 19:16 UTC, daleglass requested changes

2022-01-28 18:07 UTC, ksuprynowicz commented on interface/resources/qml/LoginDialog/LinkAccountBody.qml
> +                // ####### TODO
For security I added clearing pasword on every change of the metaverse server field.

2022-01-28 18:37 UTC, daleglass approved these changes

2022-01-28 18:40 UTC, merged