Optimize settings system
overte-org/overte pull request #236
Opened 2022-10-23 21:32 UTC by daleglass

Improve settings system, by moving all writes to a thread. This should solve stutter that may happen on systems with hard disks.
    
This should complete what was started in the HiFi days but didn't quite succeed.
    
Setting::Manager is now thread safe, and delegates all settings writes to a thread     that nothing waits on, which should ensure that settings don't degrade performance even on slow storage devices.
    
Functions that weren't thread safe were removed from Setting::Manager, and it was reduced to a key/value store.
    
Functions that modify state like beginGroup were implemented in the Settings class instead, which should be created only in the context where it's needed. It will forward all changes to the manager.
    
A few QSettings functions were left unimplemented because they're not used in the code. They may be implemented later if there's a need.

This is an alternative to #231

2022-11-01 16:51 UTC, ksuprynowicz commented
Thank you!
Everything seems to work perfectly now :)

2022-11-01 17:51 UTC, daleglass commented
Okay, finally it seems to work correctly!

* Fixed a bug with changes not being forwarded from Setting::Handle to Setting::Manager
* Fixed empty settings sometimes being loaded with a random UUID (remnant of old code)
* Improved documentation
* Added more tests
* Improved performance a bit by avoiding settings writes if nothing changes (turns out Qt code doesn't check for that)
* Improved shutdown, made sure everything is synchronized on exit (though everything should be saved near-instantly anyway)

2022-11-01 18:21 UTC, JulianGro requested changes
Please add to the copyright of SettingManager.h, SettingManager.cpp, SettingInterface.h, SettingInterface.cpp, SettingHandle.h, SettingHandle.cpp, and Application.h.

2022-11-01 19:58 UTC, JulianGro reviewed
I can't really review the code itself, but other than the commented out code that everything looks good.

2022-11-05 10:51 UTC, ksuprynowicz approved these changes
Everything looks fine to me except one typo in a comment.

2022-11-05 10:59 UTC, ksuprynowicz commented
I've been testing this PR on Linux for a week now and it works amazing - QSettings-related stutter is completely gone. I will also test it on Windows today and if it works well I suggest merging it.

2022-11-06 19:20 UTC, merged