Adding "Places" application
overte-org/overte pull request #3
Opened 2022-01-23 04:09 UTC by AleziaKurdis

This PR adds the "**Places**" application.
It sets it as a default script.

It also remove the "**Explore**" application from the default script.
But the "**Explore**" application is still available in "**Edit > Running Scripts...**" 
under "**communityScripts**" directory, for people that would like to create "beacons".

Note that the beacon's placenames are listed in the "Places" application, 
but the feature to create new ones has been left behind because that solution had serious flaws.

The "Explore" application for its part, is not geared to support multiple Metaverse Server, and it support only the Vircadia MS.
To make it flexible and use the current MS, it would have required some refactoring to send the value to the HTML layer (where it extracts the data). The explore application also have some flaws, like not filtering out the servers where the protocol is different and make them unreachable. (eventually, somewhere in the future, we could consider to retire it completely, or replace it by a lighter "beacons generation" application (possibly in More app.).

2022-01-23 06:06 UTC, JulianGro commented on scripts/defaultScripts.js
> +//  Copyright 2022 Overte contributors.
```suggestion
//  Copyright 2022 Overte e.V.
```
I would suggest already using the organization name, since it it will be able to actually enforce the license, while "Overte contributors" isn't an actual entity.

2022-01-23 20:20 UTC, AleziaKurdis commented on scripts/defaultScripts.js
> +//  Copyright 2022 Overte contributors.
Changes done 
(on 3 other files too)

2022-01-27 21:55 UTC, ksuprynowicz requested changes
I think we should change Overte e.V. to Overte contributors for now, because organization is not registered yet. Let me know what you think about it.
scripts/system/places/fonts/LICENSE.txt has placeholders in it (line 190), but it's the same in Roboto font repository, so I think we should leave it this way.
Other than that I only found one typo (Feild->Field).

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.css
> +//  Copyright 2022 Overte e.V.
```suggestion
//  Copyright 2022 Overte contributors.
```

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.html
> +//  Copyright 2022 Overte e.V.
```suggestion
//  Copyright 2022 Overte contributors.
```

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.js
> +//  Copyright 2022 Overte e.V.
```suggestion
//  Copyright 2022 Overte contributors.
```

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.html
> +                <button title="Name" class='fieldsSearchFilterOn' id='searchFilterName' onClick = 'filterSearchFeild("name");'>NAME</button>
```suggestion
                <button title="Name" class='fieldsSearchFilterOn' id='searchFilterName' onClick = 'filterSearchField("name");'>NAME</button>
```

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.html
> +                <button title="Description" class='fieldsSearchFilterOn' id='searchFilterDesc' onClick = 'filterSearchFeild("description");'>DESC</button>
```suggestion
                <button title="Description" class='fieldsSearchFilterOn' id='searchFilterDesc' onClick = 'filterSearchField("description");'>DESC</button>
```

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.html
> +                <button title="Owners" class='fieldsSearchFilterOn' id='searchFilterOwners' onClick = 'filterSearchFeild("owners");'>OWNERS</button>
```suggestion
                <button title="Owners" class='fieldsSearchFilterOn' id='searchFilterOwners' onClick = 'filterSearchField("owners");'>OWNERS</button>
```

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.html
> +                <button title="Tags" class='fieldsSearchFilterOn' id='searchFilterTags' onClick = 'filterSearchFeild("tags");'>TAGS</button>
```suggestion
                <button title="Tags" class='fieldsSearchFilterOn' id='searchFilterTags' onClick = 'filterSearchField("tags");'>TAGS</button>
```

2022-01-27 21:55 UTC, ksuprynowicz commented on scripts/system/places/places.html
> +            function filterSearchFeild(targeted) {
```suggestion
            function filterSearchField(targeted) {
```

2022-01-28 06:51 UTC, merged