Allow fullscreen display selection
overte-org/overte pull request #302
Opened 2023-01-06 16:34 UTC by daleglass

This adds an option to the graphics screen to choose which screen to use for full screen mode.

![Screenshot_20230106_153003](https://user-images.githubusercontent.com/51060919/211055483-bfba4dc2-7911-47ba-8f6b-761c77071d75.png)

It adds the API functions:

* Render.getScreens()
* Render.setFullScreenScreen(QString)
* Render.getFullScreenScreen()

Fixes #298

2023-01-06 17:10 UTC, ksuprynowicz commented
It works very well for me on Xorg

2023-01-06 18:07 UTC, akamicah approved these changes

2023-01-07 19:19 UTC, JulianGro requested changes
Would be nice if you updated the copyright headers on all of the changed files.

2023-01-07 19:19 UTC, JulianGro commented on libraries/ui/src/ScreenName.cpp
> +//  Copyright 2022 Overte e.V.
```suggestion
//  Copyright 2023 Overte e.V.
```

;)

2023-01-07 19:19 UTC, JulianGro commented on libraries/ui/src/ScreenName.h
> +//  Copyright 2022 Overte e.V.
```suggestion
//  Copyright 2023 Overte e.V.
```

2023-04-23 19:07 UTC, merged