[v8] Fix copyright headers
overte-org/overte pull request #333
Opened 2023-02-26 21:18 UTC by JulianGro

2023-02-27 23:06 UTC, ksuprynowicz requested changes
Can we keep "Created by Dale Glass on 27/8/2022" on AudioTests.h? I see no reason to remove it.

2023-02-27 23:06 UTC, ksuprynowicz commented on tests/script-engine/src/ScriptEngineTests.h
> -//  Created by Dale Glass on 27/8/2022
Can we keep this part?

2023-02-27 23:10 UTC, JulianGro commented on tests/script-engine/src/ScriptEngineTests.h
> -//  Created by Dale Glass on 27/8/2022
I just didn't know if it was created by Dale because that was clearly just copied from AudioTests.h

2023-02-27 23:20 UTC, ksuprynowicz commented on tests/script-engine/src/ScriptEngineTests.h
> -//  Created by Dale Glass on 27/8/2022
It was indeed created by Dale

2023-02-28 11:13 UTC, JulianGro commented
This is already in the v8 branch, because my git client apparently pushes to the wrong remote sometimes..

2023-02-28 11:13 UTC, closed without merging