Increase max log size
overte-org/overte pull request #342
Opened 2023-03-11 18:30 UTC by JulianGro

This PR increases the maximum log size from 512 KiB to 10 MiB, and lowers the maximum amount of log files from 100 to 20.

2023-03-11 19:54 UTC, daleglass requested changes

2023-03-11 19:54 UTC, daleglass commented on libraries/shared/src/shared/FileLogger.cpp
> +static const qint64 MAX_LOG_DIR_SIZE = 10 * 1024 * 1024 * 20;
Why not `200 * 1024 * 1024`? It would be clearer.

2023-03-11 19:56 UTC, JulianGro commented on libraries/shared/src/shared/FileLogger.cpp
> +static const qint64 MAX_LOG_DIR_SIZE = 10 * 1024 * 1024 * 20;
It is 20 times 10 MiB.

2023-03-11 21:14 UTC, daleglass commented on libraries/shared/src/shared/FileLogger.cpp
> +static const qint64 MAX_LOG_DIR_SIZE = 10 * 1024 * 1024 * 20;
Oh, duh. Okay, got to read better, n/m then.

2023-03-18 19:35 UTC, daleglass approved these changes

2023-04-14 22:35 UTC, merged