Snyk Vulnerability Checker
overte-org/overte pull request #402
Opened 2023-05-10 17:11 UTC by Colorfingers

Playing with the Snyk Vulnerability Checker and there were a few Highly Critical vulnerabilities that it found.  The suggested changes look reasonable.

https://app.snyk.io/

2023-05-10 17:12 UTC, Colorfingers commented
This is not all of the vulnerabilities... just those where upgraded sources would fix them.

2023-05-10 20:12 UTC, JulianGro commented
Did you test any of this or check what changed between these versions?

2023-05-10 21:14 UTC, Colorfingers commented
@JulianGro  I did not.

2023-05-12 18:57 UTC, ksuprynowicz requested changes
In addition to my comment above, JSdoc and server console need to be thoroughly tested for this PR.

2023-05-12 18:57 UTC, ksuprynowicz commented on android/docker/Dockerfile
> +FROM openjdk:21-ea-20-slim-bullseye
I suggest not doing this change without making sure that it works first. It will be very confusing for someone who will be working on Android version. Upgrading OpenJDK is not as trivial as changing single line.

2024-06-15 12:43 UTC, JulianGro commented
Closing, as bumping dependencies without any testing isn't helpful. If it was, we would enable Dependabot.

2024-06-15 12:43 UTC, closed without merging