Remove hifi-screenshare
overte-org/overte pull request #435
Opened 2023-05-28 12:04 UTC by JulianGro

Cherry-picked and updated from Tivoli dd5b6ea6ee5597a06603e16509640e7ed18106bb

As much of a hoarder as I am, I really don't think we will ever make use of this screen share app. The way it is currently supposed to work isn't any better than a regular web browser, and I don't think we will ever modify WebRTC to make it any better than a web browser.

Right now I am unsure if this is a protocol change, since this removed an entity property.

2023-05-28 13:28 UTC, daleglass requested changes
All good, but this leaves a tiny confusing reference in BUILD.md

2023-05-28 13:46 UTC, gydence commented on libraries/entities/src/ZoneEntityItem.cpp
> -    READ_ENTITY_PROPERTY(PROP_SCREENSHARE, uint32_t, setScreenshare);
yeah this necessitates a protocol change otherwise there will be crashes

2023-05-28 13:48 UTC, gydence commented on libraries/networking/src/udt/PacketHeaders.h
> +    DropOnProtocolChange,
we can’t just drop old versions because it messes with all the ones after.  we just have to add a new one at the end

2023-12-05 19:17 UTC, daleglass commented
It just came out that screenshare ran into some sort of problem on my Windows build. Since it's an annoyance and we don't need this, I'd like to get this one revived and merged, minus protocol break.

2024-10-19 02:38 UTC, HifiExperiments commented
superseded by #1165

2024-10-19 02:38 UTC, closed without merging