Build with crash reporting against Sentry
overte-org/overte pull request #446
Opened 2023-06-06 17:02 UTC by daleglass

Add the Sentry token so that we can report crashes.

This should be handy for the new release which includes large code changes.

2023-06-06 17:25 UTC, JulianGro requested changes

2023-06-06 17:25 UTC, JulianGro commented on .github/workflows/pr_build.yml
> +  CMAKE_BACKTRACE_URL: ${{ secrets.SENTRY_MINIDUMP_ENDPOINT }}
This will not work, as GitHub does not allow PR builds to access secrets.

2023-06-06 17:25 UTC, JulianGro commented on .github/workflows/linux_server_build.yml
> +  CMAKE_BACKTRACE_URL: ${{ secrets.SENTRY_MINIDUMP_ENDPOINT }}
This will only work for master builds, not for PR builds.
We should add a comment that this is expected to fail when being called by a PR build.

2023-06-06 17:54 UTC, daleglass commented on .github/workflows/pr_build.yml
> +  CMAKE_BACKTRACE_URL: ${{ secrets.SENTRY_MINIDUMP_ENDPOINT }}
Hm, maybe just not make it a secret then?

Sentry can have multiple endpoints, we could have one for PR builds and have it as a regular non-secret environment var.

2023-06-08 21:36 UTC, JulianGro commented on .github/workflows/pr_build.yml
> +  CMAKE_BACKTRACE_URL: ${{ vars.SENTRY_PR_MINIDUMP_ENDPOINT }}
So this doesn't seem to actually work in practice. The workflow has a seemingly empty CMAKE_BACKTRACE_URL variable and CMake prints "Checking crashpad config - CMAKE_BACKTRACE_URL is not set, disabled."

Looking around I stumbled onto [this](https://github.com/overte-org/overte/settings/variables/actions): 
> Anyone with collaborator access to this repository can use these secrets and variables for actions. **They are not passed to workflows that are triggered by a pull request from a fork.**

This implies that not only secrets don't work, but even variables don't.

I guess we should just put the endpoint URL directly into the workflow yaml files.

2023-06-11 14:02 UTC, daleglass commented on .github/workflows/pr_build.yml
> +  CMAKE_BACKTRACE_URL: ${{ vars.SENTRY_PR_MINIDUMP_ENDPOINT }}
Okay, done

2023-06-11 14:03 UTC, daleglass commented
So on the server side of things this doesn't do anything yet because there's no server-side crash reporting.

But I plan to add it in a future PR, and the environment vars won't hurt.

2023-06-11 14:09 UTC, JulianGro approved these changes

2023-06-11 14:09 UTC, JulianGro commented on .github/workflows/linux_server_build.yml
> +        if [ -z "$CMAKE_BACKTRACE_URL" ] ; then
I think it would be nicer to check again something like on.pull_request, but I have no idea how to do that so this will do.

2023-06-15 17:36 UTC, merged