Fix thumbstick press issue
overte-org/overte pull request #481
Opened 2023-06-25 22:25 UTC by ksuprynowicz

This will fix https://github.com/overte-org/overte/issues/459

2023-06-26 20:39 UTC, JulianGro requested changes
Looks logical to me except for the one comment. GCC doesn't complain.

2023-06-26 20:39 UTC, JulianGro commented on plugins/openvr/src/ViveControllerManager.cpp
> +    if (name.contains(QString("Vive")) || name.contains(QString("Vive"))) {
```suggestion
    if (name.contains(QString("Vive")) {
```
This seems redundant.

2023-06-27 19:13 UTC, ksuprynowicz commented on plugins/openvr/src/ViveControllerManager.cpp
> +    if (name.contains(QString("Vive")) || name.contains(QString("Vive"))) {
Thank you! Second "Vive" was intended to be "HTC" and would cause a bug otherwise.

2023-06-27 19:15 UTC, ksuprynowicz commented on plugins/openvr/src/ViveControllerManager.cpp
> +    if (name.contains(QString("Vive")) || name.contains(QString("Vive"))) {
I fixed it in [dfef968](https://github.com/overte-org/overte/pull/481/commits/dfef9680f97cce6b65592fa6d5a97f251a17d53a)

2023-06-27 19:16 UTC, merged