Crash handler on server
overte-org/overte pull request #482
Opened 2023-06-25 23:08 UTC by daleglass

This allows the server code to also make crash reports. This PR:

* Moves crash reporting to a new library, libmonitoring
* Refactors the code a bit
* Allows domain-server to report crashes.

Missing:
* Reporting in assignment-client
* Reporting in oven
* Web UI for configuring this

Right now to emable it, run `domain-server/domain-server --forceCrashReporting`

2023-07-02 20:47 UTC, ksuprynowicz commented
One thing I'm worried about is that domain server or assignment clients can get stuck in a crash/restart loop sometimes. In such case there could be a continuous stream of reports from a single server. Do we have a way of rate-limiting them?

2023-07-02 22:08 UTC, ksuprynowicz requested changes

2023-07-02 22:08 UTC, ksuprynowicz commented on interface/src/main.cpp
> +    QCommandLineOption noLauncherOption("no-launcher",
Previous code formatting is more readable in my opinion.

2023-07-02 23:16 UTC, daleglass commented
> One thing I'm worried about is that domain server or assignment clients can get stuck in a crash/restart loop sometimes. In such case there could be a continuous stream of reports from a single server. Do we have a way of rate-limiting them?

It can be limited on the Sentry server if needed. If it happens in a really tight loop maybe we'll need a contingency measure, but that may not belong in the crash reporter.

2023-07-03 17:32 UTC, ksuprynowicz approved these changes
Everything looks fine :)

2023-07-03 23:22 UTC, daleglass commented
I just added one last improvement: crash reporting in Oven

This proved a bit trickier than expected due to it being two applications in one.

2023-07-05 14:15 UTC, ksuprynowicz approved these changes

2023-07-05 14:15 UTC, ksuprynowicz commented on tools/oven/src/OvenCLIApplication.cpp
> +OvenCLIApplication::parseResult OvenCLIApplication::parseCommandLine(int argc, char* argv[], bool *enableCrashHandler) {
Would it be possible to use reference instead of pointer here? On the other hand pointer suggests that variable will be modified so it's fine too.

2023-07-09 19:12 UTC, ksuprynowicz approved these changes

2023-07-09 19:50 UTC, merged