Lower inertia for more precise controls
overte-org/overte pull request #542
Opened 2023-08-02 22:03 UTC by ksuprynowicz

This one needs a lot of testing. Opinions are welcome :)
Sadly there's still lag on VR input system for smooth turning and this will need to be investigated further.

2023-08-02 22:11 UTC, daleglass requested changes

2023-08-02 22:11 UTC, daleglass commented on interface/src/ui/PreferencesDialog.cpp
> +        auto getter = [myAvatar]()->float { return myAvatar->getHMDYawSpeed(); };
I think this should be:

```suggestion
        auto getter = [&myAvatar]()->float { return myAvatar->getHMDYawSpeed(); };
```

Without the reference this will copy the myAvatar object

2023-08-02 22:11 UTC, daleglass commented on interface/src/ui/PreferencesDialog.cpp
> +        auto setter = [myAvatar](float value) { myAvatar->setHMDYawSpeed(value); };
Same here:

```suggestion
        auto setter = [&myAvatar](float value) { myAvatar->setHMDYawSpeed(value); };
```

2023-08-02 22:13 UTC, daleglass approved these changes

2023-08-03 09:47 UTC, merged

2023-08-05 16:23 UTC, SilverfishVR commented
I know this is already in, but I can still have an opinion for reference.

I know the jump animation was cut to accommodate those who are not used to the delay, it never really bothered me though.  I think it looks significantly less cool without it, you just sort of pop up with no takeoff.

Flying acceleration is a lot better now, but something feels off 🤔 the acceleration curve makes it feel like I accelerate and then slow down a tiny bit. I know that is not the case but still, feels off.

2023-08-05 19:11 UTC, ksuprynowicz commented
We plan to work more on flying system sometime soon. As for jumping what do you think about having an option to toggle between two modes?

2023-08-05 19:15 UTC, JulianGro commented
I was wondering if we should have a "cinematic" mode for that sort of stuff, that people could toggle if their looks are important to them, like for performers.
Just throwing and idea at the wall for now though.

2023-08-05 19:20 UTC, ksuprynowicz commented
This sounds like a very good idea, especially since it would be very easy to do - I mostly just changed constants