:sparkles: "Update Existing Avatar" now properly updates the fst file
overte-org/overte pull request #576
Opened 2023-08-18 14:58 UTC by AnotherFoxGuy

The exporter will now keep any previous edits instead of creating a brand-new fst file

### Todo
- [x] Test multiple avatars
- [x] Cleanup the code some more

2023-09-04 20:43 UTC, AnotherFoxGuy commented
This PR should be ready for review now

2023-09-04 22:12 UTC, daleglass requested changes
Just a tiny nitpick.

I've not written any C# for ages and looking at this I've obviously gotten rusty, but at least I don't see anything obviously objectionable. A second opinion would be nice though.

Also I  don't know enough about avatars to properly evaluate what it's doing here, but that should be shown in testing.

2023-09-04 22:12 UTC, daleglass commented on tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/AvatarExporter.cs
> +    /*[MenuItem("Overte/Test")]
Should be removed

2023-09-08 20:55 UTC, daleglass approved these changes

2023-12-30 20:21 UTC, merged