Create App UI for voxels
overte-org/overte pull request #60
Opened 2022-05-01 18:06 UTC by ksuprynowicz

Do not merge yet - it's still work in progress.
This PR will extend Create App so that it will be possible to use it for creating and editing voxel entities, including in VR.

2022-05-01 20:26 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-d334e8c.sh

2022-05-03 23:15 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-acd8f85.exe

2022-05-05 20:02 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.sh

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-74498b4.exe

2022-05-06 01:23 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.tar.Z

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-5cb9fe3.exe

2022-05-06 16:23 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-92c9c89.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-92c9c89.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-92c9c89.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-92c9c89.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-92c9c89.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-92c9c89.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-92c9c89.tar.gz

2022-05-06 18:14 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-04ea6fe.exe

2022-05-07 08:12 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-60f89bc.exe

2022-05-17 18:46 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-01c2a1c.exe

2022-05-17 20:29 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-77be32c.exe

2022-05-26 07:25 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-e9b3bba.tar.gz

2022-07-03 23:23 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.tar.gz

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-abc2e37.exe

2022-07-04 01:09 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-20ff0e7.exe

2022-07-05 23:49 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ca6aa6c.exe

2022-07-09 16:04 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.sh

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-6731c55.exe

2022-07-15 01:05 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.sh

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-aeff1b9.exe

2022-07-15 21:10 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-ec33ef8.exe

2022-07-16 14:26 UTC, ksuprynowicz commented
It's ready for review and testing now :)

2022-07-16 16:57 UTC, daleglass requested changes
Some minor quibbles, but great work!

2022-07-16 16:57 UTC, daleglass commented on libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
> +
What is the purpose of these? They seem superfluous

2022-07-16 16:57 UTC, daleglass commented on scripts/system/create/editModes/editModes.js
> +            return;
Should probably log some sort of error message here, otherwise this will be very hard to debug

2022-07-16 16:57 UTC, daleglass commented on scripts/system/create/editModes/editVoxels.js
> +
Commented-out code

2022-07-16 16:57 UTC, daleglass commented on scripts/system/html/gridControls.html
> +                </select> -->
Commented-out code

2022-07-16 16:57 UTC, daleglass commented on scripts/system/html/gridControls.html
> +                <p>Click left mouse button to add voxel. Click middle mouse button to remove voxel. Hold mouse button and move mouse to add/remove voxels in a single plane. Plane is determined by the
I think the grammar could be improved here a bit, and also be more consistent with the VR version below. Eg, "Click the left mouse button to add a voxel" instead of "Click left mouse button to add voxel".

2022-07-16 16:57 UTC, daleglass commented on scripts/system/html/gridControls.html
> +                <p>Pressing trigger adds a voxel. Pressing trigger while holding grip removes it. Hold trigger to add multiple voxels in a single plane. Initial direction of controller ray determies
Maybe change it to "Press the trigger to add a voxel" to be consistent in style with the desktop version

2022-07-16 17:04 UTC, daleglass commented
I think it's good to go for a test run, my review comments shouldn't affect the functionality

2022-07-16 17:51 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.exe

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-66378eb.sh

2022-07-16 17:59 UTC, ksuprynowicz commented on libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
> +
Good catch :)
These became unnecessary after another code change optimized storage of edged voxel types.

2022-07-16 18:22 UTC, ksuprynowicz commented
Thanks for the review!
I think I fixed everything. Let me know if I missed anything.

2022-07-16 20:15 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.sh
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.sh

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-fedca74.exe

2022-07-16 21:38 UTC, daleglass requested changes

2022-07-16 21:38 UTC, daleglass commented on scripts/system/html/gridControls.html
> +                <p>Click the left mouse button to add voxel. Click the middle mouse button to remove voxel. Hold the mouse button and move mouse to add/remove voxels in a single plane. Plane is deter
I'd change this a bit more:

```suggestion
                <p>Click the left mouse button to add a voxel. Click the middle mouse button to remove a voxel. Hold the mouse button and move the mouse to add or remove voxels in a single plane. The plane is determined by the direction in which you are looking when first voxel is added or removed (for example, look downwards to draw in horizontal plane).</p>
```

2022-07-16 21:38 UTC, daleglass commented on scripts/system/html/gridControls.html
> +                <p>Press the trigger to add a voxel. Press the trigger while holding grip to remove voxel. Hold the trigger and move controller to add/remove voxels in a single plane. Plane is determ
```suggestion
                <p>Press the trigger to add a voxel. Press the trigger while holding the grip to remove a voxel. Hold the trigger and move the controller to add or remove voxels in a single plane. The plane is determined by the direction in which the controller's ray points when the first voxel is added or removed (for example point downwards to draw in the horizontal plane). Hold both grips and move your hands together or apart to change the size of the edit sphere.</p>
```

Also, "edit sphere"? Is that a thing, or you just mean it resizes the voxel?

2022-07-16 23:30 UTC, JulianGro commented on scripts/system/html/gridControls.html
> +                <p>Press the trigger to add a voxel. Press the trigger while holding grip to remove voxel. Hold the trigger and move controller to add/remove voxels in a single plane. Plane is determ
`remove voxels in a single plane.` should be `remove voxels on a single plane.`; I would argue that you cannot be inside of a 2 dimensional object.
Pretty sure it would either be `controllers` or `controllers'`, `controller's` suggests that the `s` is short for something like `is`.

2022-07-16 23:35 UTC, daleglass commented on scripts/system/html/gridControls.html
> +                <p>Press the trigger to add a voxel. Press the trigger while holding grip to remove voxel. Hold the trigger and move controller to add/remove voxels in a single plane. Plane is determ
I think it should be "controller's ray" -- a ray that belongs to the controller.  "controllers ray" doesn't make grammatical sense, and "controllers' ray" would imply there are two controllers with a single ray.

2022-07-17 10:28 UTC, ksuprynowicz commented on scripts/system/html/gridControls.html
> +                <p>Press the trigger to add a voxel. Press the trigger while holding grip to remove voxel. Hold the trigger and move controller to add/remove voxels in a single plane. Plane is determ
"Edit sphere" is a spherical brush for editing more than single voxel at once, with dimensions in world coordinate system. It's used when you switch from single voxels to spheres. You can see how its size affects editing in this video:
https://www.youtube.com/watch?v=FZOzcZsGbZM
As for controller's, you are right that in some cases it's a short for "is", like for example in "it's", but here it's a possessive 's:
https://en.wikipedia.org/wiki/English_possessive

2022-07-17 10:31 UTC, daleglass approved these changes

2022-07-17 10:45 UTC, JulianGro commented on scripts/system/html/gridControls.html
> +                <p>Press the trigger to add a voxel. Press the trigger while holding grip to remove voxel. Hold the trigger and move controller to add/remove voxels in a single plane. Plane is determ
Yeah makes sense to me. It is not `controllers'` because it refers to only one controller.

2022-07-17 10:53 UTC, ksuprynowicz commented
I also tested the server, and everything works correctly. I think it's ready for merge.

2022-07-17 11:23 UTC, merged

2022-07-17 12:06 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-b498e9e.tar.gz
 - https://public.overte.org/build/overte/PR60/Overte-PR60-b498e9e.tar.Z
 - https://public.overte.org/build/overte/PR60/Overte-PR60-b498e9e.sh

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-b498e9e.dmg

**windows-2019, full**
 - https://public.overte.org/build/overte/PR60/Overte-PR60-b498e9e.exe