Add mouse look script - continuation
overte-org/overte pull request #607
Opened 2023-08-28 20:54 UTC by rampa3

Continuation to PR #449 after tidying up branch misnaming in my repository.

2023-08-29 14:02 UTC, rampa3 commented on scripts/system/controllers/mouseLook.js
> +    function onUiFocusChanged(keyFocus) {
Check for if mouse look is enabled is now added added in 8ed70d5 - fixed.

2023-09-08 18:26 UTC, daleglass approved these changes
C++ part looks good to me

2023-09-10 05:59 UTC, ksuprynowicz requested changes
Tabs need to be converted to spaces in mouseLook.js. Otherwise everything looks fine :)

2023-09-10 13:14 UTC, ksuprynowicz approved these changes

2023-09-10 13:15 UTC, merged