Added distance-based LOD
overte-org/overte pull request #663
Opened 2023-10-13 19:37 UTC by ksuprynowicz

2023-10-13 19:55 UTC, JulianGro commented on interface/src/LODManager.h
> + * @property {number} lodFarMaxAngleDeg - The upper limit of how big the minimum angular dimension (relative to the camera position)
Why is this "MaxAngle" when it is the minimum angle? Seems pretty confusing to me.

2023-10-13 19:55 UTC, JulianGro commented on libraries/render/src/render/CullTask.cpp
> +            // threshold = args->_lodFarAngleHalfTan;
```suggestion
            // threshold = args->_lodAngleHalfTan;
```

Though I am not sure what this TODO is for. It seems as if this is done already and nothing needs to be done?

2023-10-13 19:55 UTC, JulianGro commented on interface/src/LODManager.cpp
> +    // TODO: maybe include avatar size in calculating near and far distance?
```suggestion
    // TODO: maybe include own avatar size in calculating near and far distance?
```

2023-10-13 19:56 UTC, daleglass approved these changes

2023-10-13 20:04 UTC, ksuprynowicz commented on interface/src/LODManager.h
> + * @property {number} lodFarMaxAngleDeg - The upper limit of how big the minimum angular dimension (relative to the camera position)
It's because it's the upper limit (maximum) for the minimum angular dimension.

2023-10-13 20:10 UTC, ksuprynowicz commented on libraries/render/src/render/CullTask.cpp
> +            // threshold = args->_lodFarAngleHalfTan;
This TODO means that before we had a fixed value for all the distances and right now LOD angle value changes with the distance so it assuming _lodFarAngleHalfTan seem to be obviously wrong but in tests it works. I'm marking this for the future if some unexpected problems pop up.

2023-10-14 19:24 UTC, JulianGro commented
How about "minimum target frame rate" or "lower target frame rate" for the menu setting?

2023-10-14 20:21 UTC, AleziaKurdis commented on libraries/render/src/render/CullTask.cpp
> +            // threshold = args->_lodFarAngleHalfTan;
Did you think to address the problem that we have with the current one about Material Entities that fail to be applied when very far cause material is always too small.

Example: have a big building very far but still visible (cause large), and have a material entity parented/applied on this building. when you are very far, (and never have loaded the material entity before), this one is not applied cause it is not loaded because it is too small.

2023-10-14 20:31 UTC, ksuprynowicz commented on libraries/render/src/render/CullTask.cpp
> +            // threshold = args->_lodFarAngleHalfTan;
@AleziaKurdis Can you open an issue for this with an example on which I can test? It's a very important issue and I had this problem too before (it's not caused by this PR). We should discuss it in separate issue.

2023-10-15 00:33 UTC, AleziaKurdis commented on libraries/render/src/render/CullTask.cpp
> +            // threshold = args->_lodFarAngleHalfTan;
It was already open but on under Vircadia...
So I moved the original bug in our repo:
https://github.com/overte-org/overte/issues/668

2023-10-15 08:35 UTC, JulianGro commented on interface/src/LODManager.h
> + * @property {number} lodFarMaxAngleDeg - The upper limit of how big the minimum angular dimension (relative to the camera position)
I guess what confused me is that this sets the maximum "size" that an object is allowed to have and still be culled, but the description talks about the minimum size that an object is allowed to have before being rendered.
Considering this is part of the logic for culling objects, maybe we should always describe it from a culling standpoint, instead of the rendering standpoint?
Describing the maximum as the minimum of the opposite has confused me at the very least.

2023-10-15 16:48 UTC, ksuprynowicz commented on interface/src/LODManager.h
> + * @property {number} lodFarMaxAngleDeg - The upper limit of how big the minimum angular dimension (relative to the camera position)
> Considering this is part of the logic for culling objects, maybe we should always describe it from a culling standpoint, instead of the rendering standpoint?

That's a really good idea. I described it this way in the newest PR and it's much clearer.

2023-10-16 19:08 UTC, JulianGro requested changes
Nitpicks.

2023-10-16 19:08 UTC, JulianGro commented on libraries/render/src/render/CullTask.cpp
> +            // threshold = args->_lodFarAngleHalfTan;
I still don't see a difference between
"it was":
```cpp
threshold = args->_lodFarAngleHalfTan;
```
and "now should be dependent on distance":
```cpp
threshold = args->_lodFarAngleHalfTan;
```

If what we are doing here "seems obviously wrong", maybe we should just say that instead?

2023-10-16 20:02 UTC, JulianGro approved these changes

2023-10-16 20:59 UTC, merged