Entity script logging for script editor
overte-org/overte pull request #673
Opened 2023-10-18 17:33 UTC by ksuprynowicz

2024-01-28 23:24 UTC, ksuprynowicz commented
Testing and review is needed :)

2024-01-29 21:28 UTC, daleglass requested changes

2024-02-17 13:35 UTC, ksuprynowicz commented on assignment-client/src/scripts/EntityScriptServer.cpp
> +            packet->write(data.toStdString().c_str(), data.size());
Thanks!
I fixed it in newest commit :)

2024-02-17 13:40 UTC, daleglass requested changes

2024-02-17 13:40 UTC, daleglass commented on assignment-client/src/scripts/EntityScriptServer.cpp
> +            packet->write(data.toStdString().c_str(), strlen(data.toStdString().c_str()));
How about:

```suggestion
            auto cstring = data.toStdString().c_str();
            packet->write(cstring, strlen(cstring));
```

Also, since NLPacketList is our own code, why don't we have an overload for QString instead of messing around with this?

2024-02-17 13:44 UTC, ksuprynowicz commented on assignment-client/src/scripts/EntityScriptServer.cpp
> +            packet->write(data.toStdString().c_str(), strlen(data.toStdString().c_str()));
Thanks! This looks nicer :)
As for the overload it would be a nice thing to have in the future.

2024-02-17 13:45 UTC, daleglass approved these changes

2024-02-17 13:47 UTC, daleglass commented on assignment-client/src/scripts/EntityScriptServer.cpp
> +            packet->write(data.toStdString().c_str(), strlen(data.toStdString().c_str()));
Oh, turns out we do have it!

It's `writeString`. Takes a QString as argument.

2024-02-17 14:29 UTC, ksuprynowicz commented on assignment-client/src/scripts/EntityScriptServer.cpp
> +            packet->write(data.toStdString().c_str(), strlen(data.toStdString().c_str()));
Sadly that one adds extra data and it breaks the current PR. I get an error message `[02/17 15:28:11] [WARNING] [default] EntityScriptServerLogClient::handleEntityServerScriptLogPacket: Cannot parse JSON:  "illegal value"  Contents:  "6\b"`.

2024-02-17 15:23 UTC, ksuprynowicz commented on assignment-client/src/scripts/EntityScriptServer.cpp
> +            packet->write(data.toStdString().c_str(), strlen(data.toStdString().c_str()));
It's tested and fixed now :)

2024-02-17 15:32 UTC, merged