Discord rich presence support
overte-org/overte pull request #686
Opened 2023-10-29 19:59 UTC by JulianGro

This PR adds initial Discord rich presence support using the open-source Discord-RPC library.

The privacy perspective is that this only shares data if the user:
1. Has Discord running
2. Has Rich Presence enabled in Discord (confusingly names Activitystatus and not Rich Presence)
3. Doesn't have Rich Presence disabled for Overte in Discord

![Auswahl_128](https://github.com/overte-org/overte/assets/11144627/e6ddf8ab-fa11-4d87-b7d4-28277fef2acf)

Currently, this only shows that you are playing Overte, and which Place you are at.
This is based on a Tivoli commit by Maki: https://github.com/overte-org/tivolicloud/commit/994fed2

2023-10-29 20:49 UTC, daleglass requested changes
A few quibbles, but nice work!

2023-10-29 20:49 UTC, daleglass commented on interface/src/DiscordRichPresence.cpp
> +Q_LOGGING_CATEGORY(discord_rich_presence, "hifi.discord_rich_presence")
"hifi" is a bit weird for us to use. We've used `overte.` elsewhere.

2023-10-29 20:49 UTC, daleglass commented on interface/src/DiscordRichPresence.cpp
> +    Discord_Initialize(DISCORD_APPLICATION_CLIENT_ID, nullptr, 1, "1234"); // We don't have a SteamID yet, so we use 1234
Is that a good idea? That might correspond to something else.

Probably would be good to change it to a constant with "Steam" somewhere in it, so that it can be more easily found later.

2023-10-29 20:49 UTC, daleglass commented on interface/src/Application.cpp
> +    if (_discordPresence) _discordPresence->domainChanged();
This seems a tad inelegant, in that `updateWindowTitle()` is taken as a sign of domain change.

I think we should probably be an actual domain change event somewhere? As a matter of fact this is on line 1353:

```cpp
connect(addressManager.data(), &AddressManager::hostChanged, this, &Application::updateWindowTitle);`
```

I think it'd be nicer to have domainChanged as a slot, and hook up this signal to it as well.

2023-10-29 20:49 UTC, daleglass commented on interface/src/DiscordRichPresence.h
> +#ifndef hifi_DiscordPresence_h
"hifi" is also weird here.

Also I think at this point it's perfectly fine to just use `#pragma once`

2023-10-30 17:51 UTC, JulianGro commented on interface/src/DiscordRichPresence.cpp
> +    Discord_Initialize(DISCORD_APPLICATION_CLIENT_ID, nullptr, 1, "1234"); // We don't have a SteamID yet, so we use 1234
While the variable name is `optionalSteamId` it complains when it is missing.
I don't see a dummy ID, but `1234` appears to actually be unused and is so low that I think that is likely deliberate.

I am including a constant at the start of the file like with the `DISCORD_APPLICATION_CLIENT_ID`

2023-11-02 07:52 UTC, ksuprynowicz approved these changes
Everything looks fine :)

2023-11-02 07:54 UTC, merged