Remove File API and limit audio recording file location
overte-org/overte pull request #691
Opened 2023-10-31 22:44 UTC by ksuprynowicz

2023-10-31 22:51 UTC, daleglass requested changes

2023-10-31 22:51 UTC, daleglass commented on interface/src/scripting/Audio.cpp
> +        return DependencyManager::get<AudioClient>()->startRecording(filepath + "\\" + filename);
Is that going to work on Linux?

2023-10-31 22:51 UTC, daleglass commented on interface/resources/qml/hifi/+webengine/DesktopWebEngine.qml
>      function initWebviewProfileHandlers(profile) {
Maybe remove the entire function then?

2023-10-31 22:51 UTC, daleglass commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
If two scripts start recording during the same second, there would be a conflict

2023-10-31 23:10 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        return DependencyManager::get<AudioClient>()->startRecording(filepath + "\\" + filename);
Thank you! This will probably be broken on both Linux and Windows. I will amend the commit.

2023-10-31 23:13 UTC, ksuprynowicz commented on interface/resources/qml/hifi/+webengine/DesktopWebEngine.qml
>      function initWebviewProfileHandlers(profile) {
I'd prefer leaving it, since in interface/resources/qml/hifi/DesktopWebEngine.qml it's left empty too.

2023-10-31 23:14 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
How do we resolve this with screenshots?

2023-10-31 23:18 UTC, daleglass commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
Maybe we aren't?

With screenshots you just wouldn't expect an user to mash the screenshot button. But this is an API and it's conceivable that two separate scripts might use it at the same time.

Though to be honest I'm not sure what is the intended use case for it. But as an API it should be as reliable as possible.

2023-10-31 23:29 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        return DependencyManager::get<AudioClient>()->startRecording(filepath + "\\" + filename);
Fixed!

2023-10-31 23:41 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
What would be the best way to avoid name collisions?

2023-10-31 23:45 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
Maybe to check if file exists and if it does then append an index?

2023-10-31 23:47 UTC, daleglass commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
I suppose you could just generate a random QUuid for the filename?

2023-11-01 02:01 UTC, AleziaKurdis commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
You remove completely the File API?
Wouldn't be enough to keep it only possible for interface scripts?
How are we supposed to use the saved audio file if we can't figure where it can be ?

2023-11-01 09:44 UTC, daleglass commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
> You remove completely the File API? Wouldn't be enough to keep it only possible for interface scripts? How are we supposed to use the saved audio file if we can't figure where it can be ?

There was nothing in it that would allow for doing anything with the recorded audio.

What's your use case for audio recording?

2023-11-01 12:35 UTC, ksuprynowicz commented
@AleziaKurdis The File API didn't allow reading local files. What would you say if instead stopRecording returned a byte array containing audio file which you could send for external processing either through Websocket, XMLHTTPRequest, or webengine?

2023-11-01 12:38 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
QUuid sounds like a good idea.

2023-11-01 16:02 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        QString filename = FILENAME_PATH_FORMAT.arg(username, now.toString(DATETIME_FORMAT)) + "." + DEFAULT_FORMAT;
What would be the best way to return the UUID?

2023-11-01 18:42 UTC, daleglass requested changes

2023-11-01 18:42 UTC, daleglass commented on interface/src/scripting/Audio.cpp
> +        QDateTime now = QDateTime::currentDateTime();
This seems superfluous now

2023-11-01 18:51 UTC, ksuprynowicz commented on interface/src/scripting/Audio.cpp
> +        QDateTime now = QDateTime::currentDateTime();
Thanks! Fixed :)

2023-11-01 19:01 UTC, daleglass approved these changes

2023-11-01 19:20 UTC, ksuprynowicz commented
I tested it and everything works fine

2023-11-01 19:21 UTC, merged