Fix QNetworkRequest::FollowRedirectsAttribute deprecated warning
overte-org/overte pull request #711
Opened 2023-11-08 04:58 UTC by HifiExperiments

2023-11-08 20:12 UTC, daleglass approved these changes

2023-11-15 18:51 UTC, ksuprynowicz requested changes

2023-11-15 18:51 UTC, ksuprynowicz commented on interface/src/ui/ModelsBrowser.cpp
> +        request.setAttribute(QNetworkRequest::RedirectPolicyAttribute, true);
QNetworkRequest::RedirectPolicyAttribute requires different attribute type than QNetworkRequest::FollowRedirectsAttribute, int instead of bool, which for same behavior should be QNetworkRequest::NoLessSafeRedirectPolicy. It should still work with bool, since NoLessSafeRedirectPolicy is equal to 1, but would be better to use the contant.

2023-11-19 07:13 UTC, HifiExperiments commented on interface/src/ui/ModelsBrowser.cpp
> +        request.setAttribute(QNetworkRequest::RedirectPolicyAttribute, true);
great catch, thank you!  done, and also updated copyrights.  and fixed the other 99% of the locations that I missed somehow

2023-11-24 06:40 UTC, merged