Custom refresh rate profile
overte-org/overte pull request #745
Opened 2023-11-29 22:02 UTC by squeaktoy

This adds a Custom refresh rate profile with configurable refresh rate regimes.

Unfortunately it does not work yet. The SpinBoxes inside GraphicsSettings are on top of each other, and changing the values for the Custom profile through e.g. the newly introduced JS function `Performance.setCustomRefreshRate` does not actually affect the refresh rate cap in-game at all for some reason.

2023-11-30 01:20 UTC, HifiExperiments requested changes

2023-11-30 01:20 UTC, HifiExperiments commented on interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
> +                    HifiControlsUit.SpinBox {
I'm not good at QML but I think if you put these all in a Column or Row, they wouldn't overlap?

2023-11-30 01:20 UTC, HifiExperiments commented on interface/src/RefreshRateManager.h
>      Q_ENUM(RefreshRateProfile)
`isValidRefreshRateProfile` right below here needs to be updated to `value >= RefreshRateProfile::ECO && value <= RefreshRateProfile::REALTIME`.  or even better, `value >= RefreshRateProfile::ECO && value < RefreshRateProfile::PROFILE_NUM`

2023-11-30 01:20 UTC, HifiExperiments commented on interface/src/RefreshRateManager.h
> +    std::array<int, RefreshRateRegime::REGIME_NUM> _customProfile =
for this to work, I think the profile needs to be added to REFRESH_RATE_PROFILES, and for the values to be updated there instead of this member variable.  that way, RefreshRateManager::queryRefreshRateTarget will grab the right values.

2023-11-30 14:11 UTC, JulianGro commented on interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
> +                    HifiControlsUit.SpinBox {
As far as I read the code, all the SpinBoxes have the same parent and no information about where to anchor to (which implies right after the partent, I think).
But yeah, I think HifiExperiments is right, and these should be in a Column.

2023-12-01 00:42 UTC, squeaktoy commented on interface/src/RefreshRateManager.h
>      Q_ENUM(RefreshRateProfile)
What about `value >= 0` instead of `value >= RefreshRateProfile::ECO`? I don't see why you want to be referring to an existing enum name when the point is to reference the first enum member, which is going to be 0 as long as no one makes an archaic decision to increase that number.

2023-12-01 01:06 UTC, HifiExperiments commented on interface/src/RefreshRateManager.h
>      Q_ENUM(RefreshRateProfile)
yeah that's fine too, it'd guard against someone accidentally changing the order or adding something at the beginning in the future

2024-04-17 21:47 UTC, HifiExperiments commented
thank you for doing this!  #899 was merged with these changes

2024-04-17 21:47 UTC, closed without merging