Entity tags
overte-org/overte pull request #748
Opened 2023-12-03 00:07 UTC by HifiExperiments

Adds a new entity property, `tags`, which is a set of strings used to identify an entity, and a new function `Entities.findEntitiesByTags` to search for entities with certain tags.

For some reason, tivoli implemented this and then reverted it, although their implementation used a single QString internally instead of a QSet which led to some messiness: https://github.com/tivolicloud/interface/commit/b8ad0d4d891877e48c815d35a08eaf0125c67710#diff-ee6e78795b1eed84b151c09cda884493fc5ca1201769a4e31762898be4c11df1

2023-12-30 10:03 UTC, ksuprynowicz requested changes

2023-12-30 21:42 UTC, HifiExperiments commented on libraries/entities/src/EntityTreeElement.cpp
> +                        found = true;
so true, thanks for catching that!

2023-12-30 21:45 UTC, HifiExperiments commented on libraries/entities/src/EntityScriptingInterface.h
> +        bool caseSensitiveSearch = false) const;
I think we should probably match the existing APIs, like findEntitiesByName.  the perf difference shouldn't be noticeable unless you have a truly crazy number of tags

2024-01-14 19:59 UTC, vegaslon commented
I have tested this on windows and it appears to do exactly what it says it does.

2024-01-21 19:20 UTC, merged