Fix lots of build warnings
overte-org/overte pull request #76
Opened 2022-06-05 11:27 UTC by daleglass

With this the interface build is almost clean.

This adds a warning whitelist system -- there's some stuff we just can't fix yet because we can't upgrade Qt or OpenSSL. This also adds a way to make the build fail on warning, and this is intended to be enabled by default very soon to improve code quality.

2022-06-05 15:07 UTC, daleglass commented
Pulled the contents of PR #77 into this one.

2022-06-05 19:39 UTC, JulianGro requested changes

2022-06-05 19:39 UTC, JulianGro commented on CMakeLists.txt
> +        add_compile_definitions(OVERTE_WARNINGS_WHITELIST_GLANG)
```suggestion
        add_compile_definitions(OVERTE_WARNINGS_WHITELIST_CLANG)
```

2022-06-05 19:39 UTC, JulianGro commented on CMakeLists.txt
> +    #message("Enabling warnings as errors")
This looks like it shouldn't be here.
```suggestion
```

2022-06-05 23:22 UTC, daleglass commented
Okay, this probably needs cleaning here and there, but I think content-wise it's done and ready for review.

There's a few related warnings related to glm that will be addressed later. Also there are some coming from server code that also will be addressed later.

2022-06-06 12:10 UTC, JulianGro approved these changes

2022-06-06 13:44 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-82b8743.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-82b8743.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-82b8743.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-82b8743.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-82b8743.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-82b8743.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-82b8743.tar.Z

2022-06-07 11:33 UTC, JulianGro commented
Windows builds are failing. See: https://github.com/overte-org/overte/runs/6755226576?check_suite_focus=true#step:13:290 and above

2022-06-07 19:58 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-63dfe07.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-63dfe07.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-63dfe07.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-63dfe07.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-63dfe07.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-63dfe07.tar.Z

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-63dfe07.dmg

2022-06-08 15:58 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-5fa7b49.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-5fa7b49.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-5fa7b49.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-5fa7b49.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-5fa7b49.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-5fa7b49.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-5fa7b49.sh

2022-06-08 19:55 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-e858cea.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-e858cea.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-e858cea.tar.Z

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-e858cea.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-e858cea.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-e858cea.tar.Z

2022-06-08 22:42 UTC, daleglass commented
Okay, I think I finally figured out what's the issue with Windows builds.

We're not actually doing things right in CMake here, we're trying to detect the compiler too early on Windows, and it's returning an empty string.

For now I added an ugly hack that should work. Later I'll have to do a proper PR to deal with this. It'll be a separate PR as it's also going to affect other code I used as inspiration for this work.

2022-06-09 00:05 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-2fa623d.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-2fa623d.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-2fa623d.sh

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-2fa623d.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-2fa623d.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-2fa623d.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-2fa623d.dmg

2022-06-09 16:40 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.dmg

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-35fc664.exe

2022-06-09 21:00 UTC, ksuprynowicz commented on libraries/octree/src/OctreeElement.cpp
>      qCDebug(octree).nospace() << resultString;
Why is empty string sent to qCDebug(octree).nospace()?

2022-06-09 22:50 UTC, daleglass commented
I saw some suspicious looking timeouts when testing this earlier, I might have messed up the QTimer related changes.

2022-06-10 00:39 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.tar.Z
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.tar.gz

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.tar.gz
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.sh
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR76/Overte-PR76-cdd2f9a.exe

2022-06-11 19:16 UTC, daleglass commented
Spectator camera isn't working. 

`[06/11 21:14:17] [WARNING] [hifi.qml] Unauthorized QML URL found QUrl("https://more.overte.org/applications/spectator-camera/SpectatorCamera.qml")`

This may or not be related to this PR, needs testing.

2022-06-11 19:17 UTC, daleglass commented
Settings/QML whitelist is broken

2022-06-14 19:58 UTC, daleglass commented
Server tested, everything seems to work.

2022-06-14 19:59 UTC, merged