Migrate the more app URL to Overte
overte-org/overte pull request #8
Opened 2022-02-03 03:39 UTC by AleziaKurdis

Migrate the more app URL to Overte

Note: To have this working, you need to have previously
merged the PR #1 in the overte-org/community-apps repository
AND have proceeded to its copy in the subdomain more.overte.org
It will take all this set to be working.

2022-02-20 20:01 UTC, daleglass requested changes

2022-02-20 20:01 UTC, daleglass commented on scripts/system/more/app-more.js
> +            if (runningScriptJson.indexOf("https://more.overte.org/applications") !== -1) {
This site doesn't have a valid certificate

2022-02-22 12:32 UTC, JulianGro commented on scripts/system/more/app-more.js
> +            if (runningScriptJson.indexOf("https://more.overte.org/applications") !== -1) {
The site isn't deployed yet. I assume more.overte.org currently just links to overte.org

2022-02-22 12:33 UTC, JulianGro approved these changes

2022-03-22 20:02 UTC, JulianGro requested changes
Looks good to me except for this one URL.

2022-03-22 20:29 UTC, AleziaKurdis commented on scripts/system/more/more.html
> +        Read the <a href="https://overte-org.github.io/community-apps/web/index.html">guide</a>!</p>
We read the scripts of the applications from the "more.overte.org" to run them...

But we must send the contributors to Github repo. 
(Not a big deal to send them on a site where they can't do it there. Vircadia set this like that, It was a mistake.)

2022-03-22 21:00 UTC, JulianGro commented on scripts/system/more/more.html
> +        Read the <a href="https://overte-org.github.io/community-apps/web/index.html">guide</a>!</p>
Yeah, now that you say it, this whole page doesn't really make any sense. All this information should be on the GitHub repo in a README instead of a html page here. Opening more.overte.org in a web browser should just redirect to the repo instead.

I guess the URL doesn't matter at that point. I will leave merging up to you.

2022-03-22 21:00 UTC, JulianGro approved these changes

2022-03-22 21:22 UTC, AleziaKurdis commented on scripts/system/more/more.html
> +        Read the <a href="https://overte-org.github.io/community-apps/web/index.html">guide</a>!</p>
The reason why it's an html (and not only a README), it's because it comes with a web based tool to generate the metadata.js file from the existent one to add new apps. (maybe we can have instead a README and a link to the tool instead of a webpage.)

But you are right regarding the interest to have an hyperlink... it's useless if it open in-world tablet or browser.
What we would need is an information panel in the more app to explain how and where to do it...without an hyperlink (unless we have a way to open an external browser ... I will check)

I suggest that we let this go as is for now, and I will rework this in another PR. (I would probably address the listing too by the same occasion... 3 entries per page it's a bit annoying and this pager is a bit a pain to use.)

2022-03-22 21:27 UTC, JulianGro commented on scripts/system/more/more.html
> +        Read the <a href="https://overte-org.github.io/community-apps/web/index.html">guide</a>!</p>
The metadata generator is on a different URL ( https://more.overte.org/web/metadata_js_generator.html ), so a README could just link to that instead of linking to a website that links to the metadata generator.

2022-03-25 13:46 UTC, merged