Add a way to get VCPKG path and hash ID
overte-org/overte pull request #813
Opened 2024-02-12 17:27 UTC by daleglass

This makes a simple change that aids in packaging, Docker container creation and similar:

```
$ python ./prebuild.py --get-vcpkg-id --build-root .                                                                                                                                                                                                                                       
77b4e5f4

$python ./prebuild.py --get-vcpkg-path --build-root .                                                                                                                                                                                                                                     
/home/dale/overte-files/vcpkg/77b4e5f4
```

The `--build-root .` is a requirement of the previously existing code. The value used doesn't matter for `--get-vcpkg-id` and `--get-vcpkg-path`.

A few status messages were commented out to make this more usable in a script. If they're wanted we could add a verbose or quiet mode to choose whether they show up.

2024-02-12 23:03 UTC, JulianGro requested changes
As you suggested in your PR description already, a silent mode would be more fitting than just removing those other messages.

Most of these messages log stuff that we regularly touch as part of VCPKG, Qt, or distribution updates, so I would argue that they should always be displayed by default.

2024-02-12 23:03 UTC, JulianGro commented on prebuild.py
> +        exit(0)
Since you exit anyways, maybe silencing the other log messages when using `get-vcpkg-id` or `get-vcpkg-path` would be a good option.

2024-02-12 23:05 UTC, daleglass commented on prebuild.py
> +        exit(0)
Fair enough, this was a bit lazy. I'll improve it.

2024-02-13 00:02 UTC, JulianGro requested changes
Nitpick

2024-02-13 00:02 UTC, JulianGro commented on prebuild.py
> +#print(sys.argv)
I assume this is something like ` ['/__w/overte/overte/prebuild.py', '--release-type', 'DEV', '--build-root', '/__w/overte/overte/build', '--vcpkg-build-type', 'release']`
As far as I can tell, we currently have nothing else that logs the `release-type`, so this one should stay as well.
We could change it so something just prints the release-type somewhere else instead though, then I think this message could be removed.

2024-02-13 23:32 UTC, daleglass commented on prebuild.py
> +#print(sys.argv)
fixed

2024-02-14 16:06 UTC, JulianGro approved these changes

2024-02-14 16:09 UTC, merged