glTF importer using cgltf library
overte-org/overte pull request #835
Opened 2024-02-25 19:03 UTC by ksuprynowicz

This fixes issue with ReadyPlayerMe avatars being broken and a lot of other glTF-related issues.

2024-02-25 20:31 UTC, daleglass requested changes

2024-02-25 20:31 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +        matrices.resize(matricesAccessor.count * 16);
Why 16?

2024-02-25 20:31 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +        size_t numFloats = cgltf_accessor_unpack_floats(&matricesAccessor, matrices.data(), matricesAccessor.count * 16);
Can this possibly run past the end?

2024-02-25 20:31 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +            return false;
In general, more logging would be nice. Something that leaves a trace of "hey, this file seems broken" rather than silently nothing happening.

2024-02-25 20:31 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +bool findNodeInPointerArray(const cgltf_node *nodePointer, cgltf_node **nodes, size_t arraySize, size_t &index) {
Maybe use `std::find` and the like?

2024-02-25 20:31 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                    size_t matrixCount = 16 * matrixIndex;
Are there guaranteed to be 16?

2024-02-25 20:42 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +        matrices.resize(matricesAccessor.count * 16);
It's because 4x4 matrix (cgltf_type_mat4) has 16 components

2024-02-25 20:44 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +        size_t numFloats = cgltf_accessor_unpack_floats(&matricesAccessor, matrices.data(), matricesAccessor.count * 16);
cgltf_accessor_unpack_floats() does a check against out-of-bounds access internally

2024-02-25 20:47 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +            return false;
Logging is done in buildGeometry on lines 300-304:
```
        if (!getSkinInverseBindMatrices(inverseBindValues)) {
            qDebug(modelformat) << "GLTFSerializer::getSkinInverseBindMatrices: wrong matrices accessor type for model: " << _url;
            hfmModel.loadErrorCount++;
            return false;
        }
```

2024-02-25 20:58 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                    size_t matrixCount = 16 * matrixIndex;
Thanks! I think out-of-bounds can indeed happen here. I'll have a fix in a moment.

2024-02-25 21:19 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                    size_t matrixCount = 16 * matrixIndex;
Done!

2024-02-25 21:20 UTC, daleglass approved these changes

2024-02-26 20:47 UTC, merged

2024-02-26 21:22 UTC, HifiExperiments reviewed
nice 😄

2024-02-26 21:22 UTC, HifiExperiments commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                    return false;
we used to continue here but now we completely bail.  is there a reason for that?  there are several other places like this above and below

2024-02-26 21:37 UTC, ksuprynowicz commented on libraries/model-networking/src/model-networking/ModelLoader.cpp
> +    qDebug() << "ModelLoader::load: " << url;
Thanks! That was indeed intended to be removed and I forgot. What do you thing about urls in error messages? Maybe for broken models it would make sense to log url?