Fixed blendshapes in gltf importer
overte-org/overte pull request #840
Opened 2024-02-28 21:50 UTC by ksuprynowicz

They were broken after my cgltf PR.

2024-03-01 18:49 UTC, HifiExperiments approved these changes

2024-03-01 18:54 UTC, daleglass requested changes

2024-03-01 18:54 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +        if (strcmp(nameString.c_str(), attributes->name) == 0) {
Might want to do a NULL check here just in case, seems `strcmp` may crash on null.

2024-03-01 18:54 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +    if (numFloats != accessor->count * 3) {
Is this a normal occurrence, or a defect in the file format? If it's not normal, then a log warning would be nice

2024-03-01 18:54 UTC, daleglass commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                            for (size_t j = 0; j < node.mesh->target_names_count; j++) {
You changed the loop variable to `j`, but on line 1000 you're still using `i`, is that correct?

2024-03-01 19:33 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                            for (size_t j = 0; j < node.mesh->target_names_count; j++) {
Yes, it was broken earlier due to variable being owershadowed.

2024-03-01 19:33 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +                            for (size_t j = 0; j < node.mesh->target_names_count; j++) {
So it's intentional

2024-03-02 21:41 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +    if (numFloats != accessor->count * 3) {
If this happens, it is a critical failure, and in such case generateTargetData returns false, upon which message is logged and model fails to load. It should never happen with valid glTF models.

2024-03-02 21:48 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +    if (numFloats != accessor->count * 3) {
I will change the message so that it points to problem with accessor in general instead of just accessor type.

2024-03-02 22:52 UTC, ksuprynowicz commented on libraries/model-serializers/src/GLTFSerializer.cpp
> +        if (strcmp(nameString.c_str(), attributes->name) == 0) {
Thanks for noticing this! I added a check for it.

2024-03-02 23:25 UTC, merged