Fix invalid animation reference in assignment client
overte-org/overte pull request #854
Opened 2024-03-05 00:13 UTC by ksuprynowicz

Possibly fixes assignment client (agent) animations.
Fixes https://github.com/overte-org/overte/issues/852

2024-03-05 00:14 UTC, ksuprynowicz commented
The PR started on wrong branch and I'm not sure how to fix it

2024-03-05 00:19 UTC, ksuprynowicz commented
It's ready for CR and QA now

2024-03-05 00:34 UTC, HifiExperiments commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +    auto frames = _animation->getFrames();
in `ModelEntityRenderer::animate` we use `_animation->getFramesReference()` which returns a reference instead.  I wonder if that would work here...`getFrames` is often very expensive.

2024-03-05 00:58 UTC, ksuprynowicz commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +    auto frames = _animation->getFrames();
Thanks! We were considering this too, but I was not sure about thread safety. I will add an assert there tomorrow to make sure it's on correct thread and then replace getFrames with references.

2024-03-05 23:41 UTC, ksuprynowicz commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +    auto frames = _animation->getFrames();
I fixed this part. I replaced it with reference and also added thread safety asserts just in case I got something wrong or someone changes the thread it runs on in the future.

2024-03-05 23:43 UTC, ksuprynowicz commented
For testing this creating agent client script with animated avatar would be needed. Animations in agent scripts don't seem to work in current version, so hopefully this fixes them.

2024-03-05 23:59 UTC, HifiExperiments approved these changes

2024-03-08 16:51 UTC, ksuprynowicz commented
After testing it turned out that the code was crashing and animations were still not playing.
Newest version fixes this and also fixes https://github.com/overte-org/overte/issues/720
Right now it works well when animation armature matches exactly avatar armature. Fixes for not matching armatures will come in next PR.

2024-03-08 16:53 UTC, ksuprynowicz commented
Due to a lot of changes this will need one more review

2024-03-09 02:58 UTC, HifiExperiments requested changes

2024-03-09 02:58 UTC, HifiExperiments commented on assignment-client/src/Agent.cpp
> +    DependencyManager::set<TextureCache>();
why does the agent need the TextureCache?  if this is crashing downstream somewhere, maybe we should guard it there so that we don't spend time downloading textures unnecessarily?

2024-03-09 02:58 UTC, HifiExperiments commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +        if (_animation->isLoaded() && frames.size() > 0 && _geometryResource && _geometryResource->isHFMModelLoaded() /*&& !_bind.isNull() && _bind->isLoaded()*/) {
```suggestion
        if (frames.size() > 0 && _geometryResource && _geometryResource->isHFMModelLoaded()) {
```

2024-03-09 02:58 UTC, HifiExperiments commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +                qDebug() << "!_animSkeleton";
```suggestion
```

2024-03-09 02:58 UTC, HifiExperiments commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +                qDebug() << "currentFrame: " << currentFrame;
```suggestion
```

2024-03-09 02:58 UTC, HifiExperiments commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +                    qDebug() << "lastFrame";
```suggestion
```

2024-03-09 02:58 UTC, HifiExperiments commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +                // TODO: this needs more testing
(even if this isn't perfect, seems better than before when we always used 0.01 😄)
```suggestion
```

2024-03-09 17:34 UTC, ksuprynowicz commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +        if (_animation->isLoaded() && frames.size() > 0 && _geometryResource && _geometryResource->isHFMModelLoaded() /*&& !_bind.isNull() && _bind->isLoaded()*/) {
Thanks for spotting these! I cleaned up the code and removed debug prints, commented out code, and redundant checks.

2024-03-09 17:35 UTC, ksuprynowicz commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +                // TODO: this needs more testing
Thanks! I didn't remove the comment, but I clarified it as to where the future improvements should be.

2024-03-09 17:46 UTC, ksuprynowicz commented on assignment-client/src/Agent.cpp
> +    DependencyManager::set<TextureCache>();
Sadly right now it's the best option as far as I know, at least until we can load glTF animations. Loading model as animation means that it can load only fbx ans some members of HFM model are not populated, for example joint names hash. Since this PR was focused on fixing compiler warnings, maybe we could leave future improvements for later PRs?

2024-03-09 21:27 UTC, HifiExperiments commented on assignment-client/src/Agent.cpp
> +    DependencyManager::set<TextureCache>();
hm I'm not sure I understand.  does it crash somewhere if you don't set the texture cache here?

2024-03-09 21:28 UTC, ksuprynowicz commented on assignment-client/src/Agent.cpp
> +    DependencyManager::set<TextureCache>();
Yes, it crashes because getting full model results in loading textures too.

2024-03-09 21:33 UTC, HifiExperiments commented on assignment-client/src/Agent.cpp
> +    DependencyManager::set<TextureCache>();
oh yeah ok I see in `GeometryResource::setTextures`.  could we just guard it there with `if (DependencyManager::get<TextureCache>())`?

2024-03-09 22:32 UTC, ksuprynowicz commented on assignment-client/src/Agent.cpp
> +    DependencyManager::set<TextureCache>();
Thanks! It's a very good idea. It would speed up loading and save on server RAM usage. I will try and test if it works that way. I will also add a debug print (inside `std::call_once`) that states that loading textures is disabled in such case.

2024-03-24 23:42 UTC, ksuprynowicz commented on assignment-client/src/Agent.cpp
> +    DependencyManager::set<TextureCache>();
It's fixed :)
Let me know if there's anything else to fix or we can merge

2024-03-25 02:29 UTC, HifiExperiments approved these changes
looks great 😄 

one comment you could remove + merge or just merge and we can change the comment later!

2024-03-25 02:29 UTC, HifiExperiments commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +    // TODO: the current decision to use geometry resource results in loading textures, but it works way better
can remove this TODO now!

2024-03-25 21:34 UTC, ksuprynowicz commented on assignment-client/src/avatars/ScriptableAvatar.cpp
> +    // TODO: the current decision to use geometry resource results in loading textures, but it works way better
Thanks! Done :)

2024-03-25 21:34 UTC, merged