Add qByteArray to script value conversion
overte-org/overte pull request #868
Opened 2024-03-14 00:51 UTC by ksuprynowicz

This will be useful for sending binary data such as audio streams to and from the script engine.

2024-03-14 23:18 UTC, ksuprynowicz commented
After reviewing and merging this we can work on audio streaming support

2024-04-05 21:57 UTC, daleglass requested changes

2024-04-05 21:57 UTC, daleglass commented on libraries/script-engine/src/ScriptManagerScriptingInterface.h
> +     Q_INVOKABLE QByteArray atob(const QString &base64);
Is there a reason to give it such a terse name?

2024-04-05 23:39 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptManagerScriptingInterface.h
> +     Q_INVOKABLE QByteArray atob(const QString &base64);
Yes, I'd prefer more descriptive name, but this one is standard for JS:
https://developer.mozilla.org/en-US/docs/Web/API/atob

2024-04-06 19:46 UTC, daleglass approved these changes

2024-04-16 20:34 UTC, ksuprynowicz commented
I tested it, I think it's safe to merge

2024-04-16 20:34 UTC, merged