GPU Particles
overte-org/overte pull request #884
Opened 2024-03-22 00:04 UTC by HifiExperiments

Closes #832 

Our current ParticleEffect entities have various limitations: 100,000 particles / entity, only billboarded quads, and only euler integration (position + velocity + acceleration).

This PR adds a new entity type, ProceduralParticleEffect, which gives you fine-grained control over a GPU particle system using procedural shaders for updating (per-particle updates via a fragment shader, which we can eventually convert to a compute shader) and rendering (via vertex and fragment shaders), plus higher per-system limits.

The old ParticleEffect entity is left as is, but almost all of the same functionality is possible with a ProceduralParticleEffect (everything except mesh shape emitters since we don't currently have all the mesh triangles on the GPU).  Later, we could consider deprecating it and providing a drop in ProceduralParticleEffect replacement (which could also support skinned/animated mesh emitters).  When you go to make a new particle entity in Create, it prompts you for which type you want.

On the rendering side, the particles are controlled by `particleRenderData` which acts the same way as our current procedural materials on entities.  The vertex shader must implement `vec3 getProceduralVertex(const int particleID)`, which returns the world space position of the vertex.  By default, 1 triangle is drawn per particle, so that function will be run 3 times per particle (with different `gl_VertexID`s), but this can be controlled by `numTrianglesPerParticle` (see the 3rd example below).  The fragment shader must implement one of the same functions as our existing procedural materials depending on version: `vec3 getProceduralColor()`, `float getProceduralColors(inout vec3 diffuse, inout vec3 specular, inout float shininess)`, `float getProceduralFragment(inout ProceduralFragment proceduralData)`, or `float getProceduralFragmentWithPosition(inout ProceduralFragmentWithPosition proceduralData)`.  In the fragment shader, `particleID` is available as a global variable.  One difference between procedural particles and procedural materials on other entities is that they do *not* have per-fragment normals or uvs defined by default, you must calculate them yourself if you want lit or textured particles (see the 3rd example below).

Per-particle updates are optional.  They can be used to store persistent per-particle data across frames or reduce calculations in the rendering shaders.  To activate updates, `numUpdateProps` must be > 0 (max is 5) and you must provide a fragment shader as part of `particleUpdateData`.  Each "update prop" is a per-particle vec4 of float values.  The update shader must define `void updateParticleProps(const int particleID, inout ParticleUpdateProps particleProps)`.  `particleProps` will contain as many update props as you specified (e.g. if `numUpdateProps == 3`, you'll have `particleProps.prop0`, `particleProps.prop1`, and `particleProps.prop2`).  They will initially contain all 0s, and then will persist any values from previous frames.  You can look up these properties during rendering with `vec4 getParticleProperty(const int propIndex, const int particleID)` in both the vertex and fragment shaders.

Like the old ParticleEffect, transparent particles (`particleTransparent == true`) render with additive blending since they are unsorted.

Notes + follow up work:
- Shaders are hard.  We should create a library of simple effects that can be driven by scripts/uniforms and add them to Create as presets.
- Currently, you have to do some heavy lifting in your vertex shader to create shapes, especially if you want lighting (which require you to calculate normals).  We could probably add a property like "particleShape" with a "custom" mode that would mirror this behavior, but also provide things like "sphere", "billboarded quad/triangle", and "model" (although that'll be trickier) to easily draw each particle as those shapes (which could then be adjusted in the vertex shader).

## Examples
Cube of oscillating, unlit, billboarded triangles, no update:
```
Entities.addEntity({
	type: "ProceduralParticleEffect",
	position: Vec3.sum(MyAvatar.position, Vec3.multiply(4, Quat.getFront(MyAvatar.orientation))),
	dimensions: 3,
	numParticles: 10000,
	numTrianglesPerParticle: 1,
	numUpdateProps: 0,
	particleRenderData: JSON.stringify({
		version: 1.0,
		vertexShaderURL: "https://gist.githubusercontent.com/HifiExperiments/1c1f83814b332782b590f44eca329fc4/raw/51753492e8634858239d57d6b8fb0f136a9f49af/proceduralParticle.vs",
		fragmentShaderURL: "https://gist.githubusercontent.com/HifiExperiments/7def54504362c7bc79b5c85cd515b98b/raw/93b3828c2ec66b12b789a625dd141f533c595ede/proceduralParticle.fs",
		uniforms: {
			radius: 0.03
		}
	})
})
```
![overte-snap-by--on-2024-03-17_22-28-49](https://github.com/overte-org/overte/assets/53453710/f09c09a0-fa4a-432f-8674-58ba18f0a274)

Same cube of oscillating, unlit, billboarded triangles, but with the oscillation in the update (computed once per particle instead of once per vertex):
```
Entities.addEntity({
	type: "ProceduralParticleEffect",
	position: Vec3.sum(MyAvatar.position, Vec3.multiply(4, Quat.getFront(MyAvatar.orientation))),
	dimensions: 3,
	numParticles: 10000,
	numTrianglesPerParticle: 1,
	numUpdateProps: 1,
	particleUpdateData: JSON.stringify({
		version: 1.0,
		fragmentShaderURL: "https://gist.githubusercontent.com/HifiExperiments/9049fb4a8dcd2c1401ff4321103dce16/raw/4f9474ed82c66c1f94c1055d2724af808cd7aace/proceduralParticleUpdate.fs",
	}),
	particleRenderData: JSON.stringify({
		version: 1.0,
		vertexShaderURL: "https://gist.github.com/HifiExperiments/5dda24e28e7de1719e3a594d81306343/raw/92e0c5b82a9fa87685064cdbab92ed0c16f49f94/proceduralParticle2.vs",
		fragmentShaderURL: "https://gist.github.com/HifiExperiments/7def54504362c7bc79b5c85cd515b98b/raw/93b3828c2ec66b12b789a625dd141f533c595ede/proceduralParticle.fs",
		uniforms: {
			radius: 0.03
		}
	})
})
```

Swarm of 3D particles simulating gravity, colored with their normals, lit:
```
Entities.addEntity({
	type: "ProceduralParticleEffect",
	position: Vec3.sum(MyAvatar.position, Vec3.multiply(6, Quat.getFront(MyAvatar.orientation))),
	dimensions: 3,
	numParticles: 10000,
	numTrianglesPerParticle: 6,
	numUpdateProps: 3,
	particleUpdateData: JSON.stringify({
		version: 1.0,
		fragmentShaderURL: "https://gist.github.com/HifiExperiments/5e87462f7be127882a1657c463c3638f/raw/d7cd4b3e83b0bfe740e5c93b65f2455b38b8341f/proceduralParticleUpdate2.fs",
		uniforms: {
			lifespan: 3.0,
			speed: 2.0,
			speedSpread: 0.25,
			mass: 50000000000
		}
	}),
	particleRenderData: JSON.stringify({
		version: 3.0,
		vertexShaderURL: "https://gist.github.com/HifiExperiments/f0a86ecd37dedde3a2d187373a9117d1/raw/1fe678f0e28130839deab4fff8d04c279cdd1581/proceduralParticle3.vs",
		fragmentShaderURL: "https://gist.github.com/HifiExperiments/2174e4cbff17fbeb4390353e6791920f/raw/fd6abf3f8bb21fc3fbd58e2aa0c47fd895352789/proceduralParticle2.fs",
		uniforms: {
			radius: 0.03,
			lifespan: 3.0
		}
	})
})
```
![overte-snap-by--on-2024-03-17_22-34-04](https://github.com/overte-org/overte/assets/53453710/26607f00-6959-43bb-bd14-56d4e3accb92)

## Funding

This project is funded through [NGI0 Entrust](https://nlnet.nl/entrust), a fund established by [NLnet](https://nlnet.nl) with financial support from the European Commission's [Next Generation Internet](https://ngi.eu) program. Learn more at the [NLnet project page](https://nlnet.nl/project/Overte).

[<img src="https://nlnet.nl/logo/banner.png" alt="NLnet foundation logo" width="20%" />](https://nlnet.nl)
[<img src="https://nlnet.nl/image/logos/NGI0_tag.svg" alt="NGI Zero Logo" width="20%" />](https://nlnet.nl/entrust)

2024-03-22 00:25 UTC, HifiExperiments commented on libraries/entities-renderer/src/RenderableProceduralParticleEffectEntityItem.cpp
> +    batch.draw(gpu::TRIANGLE_STRIP, 4);
we don't currently support compute shaders, so the update pass is implemented as a fragment shader operating on textures instead of buffers.  once we have them (presumably with Vulkan), we can revisit this and theoretically increase performance.

2024-03-22 00:25 UTC, HifiExperiments commented on libraries/entities/src/EntityItemProperties.cpp
> + * @example <caption>TODO</caption>
an open question: what would we like the example here (and the default in edit.js) to be?

2024-03-22 00:25 UTC, HifiExperiments commented on scripts/system/create/entityProperties/html/js/entityProperties.js
> +/**
adding new JSON areas kinda sucks.  this is directly copied from the other JSON props, but we should probably generalize it in the future so we don't have to repeat all of this...

2024-03-22 18:47 UTC, vegaslon commented
certainly looks interesting https://gyazo.com/f33d97de2202fc94c399e919ca1ac3e6

2024-03-22 19:12 UTC, HifiExperiments commented
@vegaslon ah, forgot to mention, they use their dimensions directly as their bounding box, like our existing procedural vertex shaders via material entities, since we don't know on the CPU where the shader is going to place the particles.  so you can just make their dimensions bigger and they won't get culled like that.

once we merge this, I will put up a page in the docs with these details

2024-03-22 21:32 UTC, SilverfishVR commented
a minor alignment issue:


![Screenshot 2024-03-22 221126](https://github.com/overte-org/overte/assets/53531160/d35e79a8-766c-4870-bd7d-7ae703f125f1)

2024-03-23 07:32 UTC, JulianGro commented
You can probably just get rid of the "Num" for the numbers. If someone is unsure, they can look at the tooltip.

2024-03-24 03:52 UTC, HifiExperiments commented
here's two more basic examples, these also show how we'd re-implement some of the existing CPU particle properties (emitDimensions, speed, speedSpread, acceleration):

[Particles bouncing off a 3D plane, driven by a plane entity](https://gist.githubusercontent.com/HifiExperiments/ba61fc4f50300fc48f3999dd3e921b8d/raw/56d6b563bcdafa379004c05d8bc73e0d2fb7ba56/GPUParticlesPlane.js)
![overte-snap-by--on-2024-03-22_21-12-34](https://github.com/overte-org/overte/assets/53453710/e331867d-3c7d-4abe-84ad-d81741740c92)

[Particles attracted to another entity](https://gist.githubusercontent.com/HifiExperiments/7970182314d28448864bb6144235c25e/raw/23773345a8aaf8679732f9e17bcd4deea4cb1a72/GPUParticlesAttractor.js)
![overte-snap-by--on-2024-03-23_16-34-40](https://github.com/overte-org/overte/assets/53453710/704c041b-90b0-4d1c-a029-8539217bb4e9)

2024-03-29 21:22 UTC, vegaslon commented
https://i.gyazo.com/d93a81979e5dbe7ce76b3249a3445889.mp4 ok that is seriously really neat

2024-04-09 21:24 UTC, ksuprynowicz requested changes
This is seriously cool :)
All looks fine, except single unused variable

2024-04-17 22:44 UTC, HifiExperiments commented on scripts/system/create/qml/NewParticleDialog.qml
> +    property bool keyboardRasied: false
thank you for noticing this!  turns out we had this typo in all of the new entity dialogs and we've just been copying it around for years 🙃.  I removed it from them all.

2024-04-17 22:46 UTC, HifiExperiments commented on libraries/entities/src/EntityItemProperties.cpp
> + * @example <caption>TODO</caption>
I've changed this example to show the cube of oscillating particles and the default in create to be the swarm of 3D particles.  I hope they show off the range of functionality.  We can continue messing with these and adding more options and examples over time

2024-04-18 18:55 UTC, HifiExperiments commented
I've fixed the typo and added a default effect to create.  unless anyone has any more thoughts this is ready to be merged from my side!

2024-04-18 19:02 UTC, vegaslon commented
Always hard to test something brand new like this and so I have no complaints with what I have found. I figured this could only be held up by things like what standard of ease of usability does it need to go for or some such. Before it is considered merge able. 

My opinion is this is good enough right now to merge and any addition assistance to make it more usable can be created with addition examples down the line and a app to help, like what happened to material entities, before the create app is modified.

2024-04-19 20:35 UTC, daleglass approved these changes

2024-04-19 20:41 UTC, merged