Added simple protection for avatar URL
overte-org/overte pull request #887
Opened 2024-03-23 00:22 UTC by ksuprynowicz

This adds simple permissions system to script engines.
As an example permission, setting to protect avatar URL is added here.
This PR also prevents getting other people's avatar URLs.
It's still work in progress - I need to add protection for avatar URL setting entry and bookmarks.

2024-03-23 00:52 UTC, vegaslon commented
The actual bookmark names or thumbnails that you can define in them might be useful for casuals scripts to use for the purpose of nametags or some other idea.

2024-03-23 00:58 UTC, ksuprynowicz commented
> The actual bookmark names or thumbnails that you can define in them might be useful for casuals scripts to use for the purpose of nametags, or a wardrobe app etc.

Yes. The PR whitelists all local filesystem, tutorial and community apps scripts for this reason and provides simple UI for whitelisting more scripts and also for disabling this system entirely and allowing all scripts.

Future PRs will also contain UI that will allow scripts to ask for required permissions.

2024-03-24 21:38 UTC, ksuprynowicz commented
This is now ready for code review and testing. Please let me know if it breaks anything.

2024-03-26 11:36 UTC, vegaslon commented
avatar textures are broken on windows.
![overte-snap-by--on-2024-03-26_07-36-26](https://github.com/overte-org/overte/assets/2307946/c3192244-ee46-4505-969d-d4cb96eae39a)

2024-03-26 12:39 UTC, vegaslon commented
not caused by this pr but https://github.com/overte-org/overte/pull/854 which was merged between test builds

2024-03-26 23:45 UTC, HifiExperiments requested changes
this is a very cool idea!  the detection of which script we're in seems super powerful!  I had a few questions/comments

2024-03-26 23:45 UTC, HifiExperiments commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +        var arrayWhitelist = whitelist.split(",").join("\n");
could this just be 
```suggestion
        var arrayWhitelist = whitelist.replace(",", "\n");
```

similar below

2024-03-26 23:45 UTC, HifiExperiments commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +        setWhitelistSuccess(arrayCheck === originalSet);
why would this fail?

2024-03-26 23:45 UTC, HifiExperiments commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +    function toggleWhitelist(enabled) {
this function doesn't really toggle the value, so maybe a different name?

2024-03-26 23:45 UTC, HifiExperiments commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +            whitelistEnabled.toggle();
does this have to be done in the `onCompleted` or can you just set the initial value to `Settings.getValue("private/scriptPermissionGetAvatarURLEnable", true)` directly?

2024-03-26 23:45 UTC, HifiExperiments commented on interface/src/CrashRecoveryHandler.cpp
> +        settings.setValue(SETTINGS_FULL_PRIVATE_GROUP_NAME + "/" + AVATAR_GROUP + "/" + FULL_AVATAR_URL_KEY, fullAvatarURL);
do you need to delete the line above here that sets `FULL_AVATAR_URL_KEY`?

2024-03-26 23:45 UTC, HifiExperiments commented on interface/src/avatar/MyAvatar.cpp
> +    _fullAvatarURLSetting(QStringList() << SETTINGS_FULL_PRIVATE_GROUP_NAME << AVATAR_SETTINGS_GROUP_NAME << "fullAvatarURL",
do you need a "/" in here?

2024-03-26 23:45 UTC, HifiExperiments commented on interface/src/scripting/SettingsScriptingInterface.cpp
> +    if (_restrictPrivateValues && setting.startsWith(SETTINGS_FULL_PRIVATE_GROUP_NAME + "/")) {
should this check and the one below be at the beginnings of these functions to avoid the calls to Setting::Handle::get (for perf more than security)

2024-03-26 23:45 UTC, HifiExperiments commented on libraries/avatars/src/AvatarData.cpp
> +    }
could simplify this:

```suggestion
    if (isMyAvatar() && !isMyAvatarURLProtected()) {
        return _skeletonModelURL.toString();
    }

    return QString();
```

2024-03-26 23:45 UTC, HifiExperiments commented on libraries/avatars/src/ScriptAvatarData.cpp
> +        }
similar here:

```suggestion
        if (sharedAvatarData->isMyAvatar() && !sharedAvatarData->isMyAvatarURLProtected()) {
            return sharedAvatarData->getSkeletonModelURLFromScript();
        }

        return QString();
```

2024-03-26 23:45 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptPermissions.cpp
> +    std::vector<QString> urlsToCheck;
you add things to urlsToCheck but do you actually check them somewhere?

2024-03-26 23:45 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptPermissions.cpp
> +        while (parentContext) {
just to clarify, does this mean that if a script calls another script, every script up the chain must be whitelisted?

2024-03-26 23:45 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptPermissions.cpp
> +    QList<QString> allowedURLs = allowedURLsSetting.get().split("\n");
in the QML, it seems like the whitelist is comma separated, but here you're splitting on \n, is that right?

2024-03-26 23:45 UTC, HifiExperiments commented on libraries/shared/src/SpatiallyNestable.h
> +    virtual bool isMyAvatarURLProtected() const { return false; } // This needs to be here because both MyAvatar and AvatarData inherit from MyAvatar
can you explain this?  MyAvatar inherits from Avatar which inherits from AvatarData, so you should be able to just put this in AvatarData, no?

2024-04-12 22:43 UTC, ksuprynowicz commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +        setWhitelistSuccess(arrayCheck === originalSet);
I got the original from EntityScriptQMLWhitelist.qml and I'm not sure what it did originally. Since Dale completely rewrote settings, maybe we could just remove that part?

2024-04-13 17:40 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptPermissions.cpp
> +    QList<QString> allowedURLs = allowedURLsSetting.get().split("\n");
In whitelist it can be either comma or newline separated, commas are replaced with newline charaters, so on C++ it's newline separated.

2024-04-13 17:42 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptPermissions.cpp
> +        while (parentContext) {
Indeed. Otherwise a malicious script could include one of default scripts which are whitelisted and call a function from there to get elevated security level.

2024-04-13 17:49 UTC, ksuprynowicz commented on libraries/script-engine/src/ScriptPermissions.cpp
> +    std::vector<QString> urlsToCheck;
Thank you for catching this! It's indeed meant to be checked later - otherwise it would introduce a security vulnerability.

2024-04-13 20:35 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptPermissions.cpp
> +    QList<QString> allowedURLs = allowedURLsSetting.get().split("\n");
ooooooh I see, makes sense!

2024-04-13 22:48 UTC, ksuprynowicz commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +    function toggleWhitelist(enabled) {
Agreed. The name is confusing. I'll rename it to `setAvatarProtection`.

2024-04-13 23:38 UTC, ksuprynowicz commented on interface/src/avatar/MyAvatar.cpp
> +    _fullAvatarURLSetting(QStringList() << SETTINGS_FULL_PRIVATE_GROUP_NAME << AVATAR_SETTINGS_GROUP_NAME << "fullAvatarURL",
It's automatically added in a constructor:
`Handle(const QStringList& path) : Interface(path.join("/")) {}`

2024-04-14 16:00 UTC, ksuprynowicz commented on interface/src/CrashRecoveryHandler.cpp
> +        settings.setValue(SETTINGS_FULL_PRIVATE_GROUP_NAME + "/" + AVATAR_GROUP + "/" + FULL_AVATAR_URL_KEY, fullAvatarURL);
Thank you! I missed that one

2024-04-14 18:26 UTC, ksuprynowicz commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +        setWhitelistSuccess(arrayCheck === originalSet);
I removed it in the newest PR - I don't think there's a reason it would ever fail.

2024-04-14 19:58 UTC, ksuprynowicz commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +            whitelistEnabled.toggle();
Thanks!
It does work this way and it's much simpler.

2024-04-14 20:12 UTC, ksuprynowicz commented on libraries/shared/src/SpatiallyNestable.h
> +    virtual bool isMyAvatarURLProtected() const { return false; } // This needs to be here because both MyAvatar and AvatarData inherit from MyAvatar
Thanks! I didn't notice that MyAvatar inherited from AvatarData - I moved `isMyAvatarURLProtected` to AvatarData now.

2024-04-14 20:17 UTC, ksuprynowicz commented on interface/resources/qml/hifi/dialogs/security/ScriptSecurity.qml
> +        var arrayWhitelist = whitelist.split(",").join("\n");
Fixed!

2024-04-14 20:43 UTC, ksuprynowicz commented
@HifiExperiments Thank you for the review! Let me know if there's anything else to fix :)
In the meantime I think this PR is ready for testing.

2024-04-14 21:07 UTC, HifiExperiments approved these changes
love it, thanks for making those changes. looks great to me 😃

2024-04-16 19:01 UTC, vegaslon commented
Script protection can not be turned off for untrusted sources . As a test try running this script https://raw.githubusercontent.com/danteruiz/hifi-content/dcad0fc0c16520815654c6a2f3cc12a11c1230e4/debug/avatarTest.js

2024-04-16 22:48 UTC, ksuprynowicz commented
Fixed!
Should work well now.

2024-04-17 20:49 UTC, vegaslon commented
Yep works now, have not found any more bugs

2024-04-17 20:50 UTC, ksuprynowicz commented
If there's no more problems I think this can be safely merged.

2024-04-18 22:16 UTC, merged