Refactor Application.cpp
overte-org/overte pull request #939
Opened 2024-04-16 21:29 UTC by HifiExperiments

(apologies to whoever reviews this)

Application.cpp has gotten totally out of control over the years (in many cases because of my dumb decisions).  This is an attempt to corral it.  I've organized the code as best I could into sections - Assets, Camera, Entities, Events, Graphics, Plugins, Setup, and UI - and divided the implementations into separate, smaller files.  I completely rebuilt the includes from scratch so we only have what's necessary.  I broke some of the classes into their own files.  Overall, I changed very little functionally.  I removed a few unused variables and functions but nearly everything is directly copy-pasted.

Testing-wise, things should just work as before.  In particular, anything related to startup, login UI, and plugins.

## Funding

This project is funded through [NGI0 Entrust](https://nlnet.nl/entrust), a fund established by [NLnet](https://nlnet.nl) with financial support from the European Commission's [Next Generation Internet](https://ngi.eu) program. Learn more at the [NLnet project page](https://nlnet.nl/project/Overte).

[<img src="https://nlnet.nl/logo/banner.png" alt="NLnet foundation logo" width="20%" />](https://nlnet.nl)
[<img src="https://nlnet.nl/image/logos/NGI0_tag.svg" alt="NGI Zero Logo" width="20%" />](https://nlnet.nl/entrust)

2024-04-17 02:19 UTC, HifiExperiments commented on interface/src/Application.h
> -    bool _profilingInitialized { false };
oh yeah @daleglass it didn't look like this was ever set to true, so I deleted it + the one place it was used, is that ok?

2024-04-17 19:29 UTC, HifiExperiments commented
hm

```
/__w/overte/overte/interface/src/scripting/PerformanceScriptingInterface.cpp:14:10: fatal error: QtQML: No such file or directory
   14 | #include <QtQML>
      |          ^~~~~~~
```

I'll look into that...

2024-04-17 19:47 UTC, HifiExperiments commented on interface/src/Application.h
> -    bool _profilingInitialized { false };
it seemed to be working ok for me without it, maybe if it's a problem during testing I can add it back?

2024-04-17 19:49 UTC, daleglass commented on interface/src/Application.h
> -    bool _profilingInitialized { false };
Sure, it's simple enough that it'd be easy. I did quite a lot of rearranging of that code, and right now can't recall if maybe I just fixed this in some other way in the end.

2024-06-07 21:38 UTC, ksuprynowicz requested changes
This is really awesome :)
Application.cpp needed refactoring badly and this will make future work a lot easier.
I didn't find any problems, but I have few questions and I found what I think is earlier thread safety issue in the code.

2024-06-07 21:47 UTC, ksuprynowicz commented on interface/src/ApplicationMeshProvider.h
> +        if (auto entity = entityTree->findEntityByID(entityID)) {
Maybe as a later PR we should do a thread safety audit of all the places where entity tree is used?

2024-06-08 07:28 UTC, ksuprynowicz commented
I'm also having trouble building it on Linux using Overte-builder:
![image](https://github.com/overte-org/overte/assets/11568651/fcfe0b20-3ea9-4913-8224-2f811efa8ada)

2024-06-10 05:43 UTC, HifiExperiments commented on interface/src/ApplicationMeshProvider.h
> +        if (auto entity = entityTree->findEntityByID(entityID)) {
oh wow great catch.  `EntityTree::findEntityByID` actually calls `EntityTree::findEntityByEntityItemID` which does internally use a read lock, but then `EntityTreeRenderer::renderableForEntityId` looks like it needs it?  I filed https://github.com/overte-org/overte/issues/1015

2024-06-10 05:43 UTC, HifiExperiments commented on interface/src/Application.cpp
> +    //DependencyManager::get<LODManager>()->setAutomaticLODAdjust(false);
done!

2024-06-10 05:43 UTC, HifiExperiments commented on interface/src/Application_Assets.cpp
> +                ((filePath.toLower().endsWith(JPG_EXTENSION) || filePath.toLower().endsWith(PNG_EXTENSION)) &&
done!

2024-06-10 05:50 UTC, HifiExperiments commented on interface/src/Application_Setup.cpp
> +
huh maybe?  how do I do that?

2024-06-15 15:30 UTC, ksuprynowicz commented
I tested it on Windows, and it asks to log in every time. A different than usual login screen is used for this:
![overte-snap-by--on-2024-06-15_15-10-47](https://github.com/overte-org/overte/assets/11568651/0e0f7b82-17ee-4b17-8abd-681c121d3cf9)
 Kraftwerk world becomes entirely white after skybox loads:
 
![overte-snap-by--on-2024-06-15_15-02-21](https://github.com/overte-org/overte/assets/11568651/5c00dc5f-1e97-4f6b-8494-d20cf2551628)
No audio devices are detected:
![obraz](https://github.com/overte-org/overte/assets/11568651/84a3f726-0dbc-4cef-9e41-e049507d2bac)

2024-06-15 15:30 UTC, ksuprynowicz commented
It also seems that login screen that it uses in VR is intended for desktop?

2024-06-15 15:32 UTC, ksuprynowicz commented
The good thing about that different login screen though is that it has option to continue anonymously. Ours is badly missing this.

2024-06-20 21:53 UTC, HifiExperiments commented
I believe I've fixed the audio device issue.  for the login screen, it turns out I had accidentally deleted `_disableLoginScreen` which was always set to true.  so whatever that fullscreen login page was for, it appears to have been disabled intentionally at some point.  I've re-disabled it to just avoid messing with stuff, but maybe we should look into re-enabling it properly at some point.  I'm not sure if this also fixed the VR login screen, if that's still a problem could you send me a screenshot?

I wasn't able to reproduce the issue in kraftwerk; I wonder if the download got corrupted or something?  does it still happen if you clear your caches, including ktx cache?

2024-09-02 15:07 UTC, JulianGro commented
I gave this a test on Linux and so far, everything works fine. I tried clearing shader cache and ktx cache as well. In both scenarios, Kraftwerk renders properly.

2024-09-12 20:06 UTC, ksuprynowicz commented
I tested it again and now everything works well :)

2024-09-12 20:07 UTC, ksuprynowicz commented
Would someone like to test in VR on Windows? I don't have a VR setup at the moment. If all works well we could merge it.

2024-09-12 20:58 UTC, HifiExperiments commented
there are some conflicts now, I’ll probably wait until after the next release to rebase and resolve them just to avoid causing any problems

2024-09-13 04:39 UTC, Armored-Dragon commented
> Would someone like to test in VR on Windows? I don't have a VR setup at the moment. If all works well we could merge it.

I did some brief testing in VR and everything seems to work as expected. 

> there are some conflicts now, I’ll probably wait until after the next release to rebase and resolve them just to avoid causing any problems

I will also take a look at this again after the rebase!

2024-10-22 04:03 UTC, HifiExperiments commented
I've rebased this and it's all ready to be reviewed + tested again!

2025-01-05 06:40 UTC, HifiExperiments commented
I've rebased this again and it's still ready for final testing + review!

2025-01-05 17:41 UTC, ksuprynowicz commented
I just tested it on Linux and on every start no microphone is selected. Default microphone needs to be selected every start. Output seems to be selected properly.

2025-01-05 18:23 UTC, ksuprynowicz commented
It seems that microphone issue happens only on Linux. It happens on every start and no input is selected:
![image](https://github.com/user-attachments/assets/ed960112-ed32-4eb4-ac65-c0ce676a391b)

2025-01-05 18:37 UTC, ksuprynowicz commented
It looks like the microphone issue doesn't happen in Desktop mode on Windows, but does happen in VR mode on Windows, exactly like in Desktop mode on Linux.

2025-01-05 18:49 UTC, ksuprynowicz commented
Teleport script in the tower near Overte_hub spawn point is broken, it fails with message:
```
[01/05 19:47:37] [CRITICAL] [overte.scriptengine] [about:Entities 1] Function call failed: "failed on line 26 column 8 with message: "Uncaught ReferenceError: Window is not defined" backtrace: ReferenceError: Window is not defined
[01/05 19:47:37] [CRITICAL] [overte.scriptengine]     at Object.enterEntity (https://aleziakurdis.github.io/inertia/teleporters/teleporter.js:26:9)
[01/05 19:47:37] [CRITICAL] [overte.scriptengine] [about:Entities 1] JS function call failed:
```

2025-01-06 09:49 UTC, ksuprynowicz commented
After some more testing input selection issue seems to happen sometimes in Desktop mode on Windows too.

2025-01-07 05:08 UTC, HifiExperiments commented
darn!  thank you for testing, I'll look into those

2025-02-19 05:06 UTC, HifiExperiments commented
there’s definitely some weirdness around audio devices on startup.  the previous fix (to the much earlier issue of the audio devices not showing up) was to reorder some initialization: https://github.com/overte-org/overte/pull/939/commits/2345bcc2b58d2cb8560cbabcca65f191ee0e81de#diff-379416a9df19174e2bf0d9d644da8269931fbe2f7f0516719eedb75f8d022b34R810

so…perhaps there’s still something wrong about the order of that versus the loading from settings

2025-02-22 06:41 UTC, HifiExperiments commented
thanks again to @ksuprynowicz, the audio issue appears to be fixed!

I haven't looked at the teleport issue yet, if that's still an issue I will take a look this weekend, but otherwise I think this is ready for more testing

2025-02-24 16:33 UTC, ksuprynowicz commented
We did a lot of testing on the newest version of this PR, both in desktop and VR. All seems to work good :)

2025-02-24 17:41 UTC, HifiExperiments commented
amazing!  this is ready to merge then from my side. 🎉

2025-02-24 19:33 UTC, ksuprynowicz approved these changes
Everything looks good :)

2025-02-24 19:35 UTC, merged

2025-02-24 20:12 UTC, HifiExperiments commented
HUGE thank you @ksuprynowicz for all your help with this!

2025-02-24 20:19 UTC, ksuprynowicz commented
@HifiExperiments Thank you for the refactor - it was a massive undertaking and was really needed with how big Application.cpp got XD