Replace Floofchat with ArmoredChat
overte-org/overte pull request #961
Opened 2024-05-17 21:39 UTC by Armored-Dragon

Part of #886 
Replace Floofchat with a smaller application using written in QML.

![image](https://github.com/overte-org/overte/assets/43324896/939139be-138f-4619-a77c-e5b43d7c71e7)
![image](https://github.com/overte-org/overte/assets/43324896/290e293e-2e74-4f1a-a006-cb46dd6d270a)

## Compatibility 
This version of Armored Chat is not compatible with Floofchat. 
Armored Chat is still compatible with [notificationCore.js](https://github.com/overte-org/overte/tree/master/scripts/communityScripts/notificationCore).

## Todo:
- [ ] Embedding
    - Handle link embeds
    - (Potentially) handle special embeds like YouTube and GitHub
- [ ] Selective auto-scroll
    - Prevent scrolling to newest chat message if the view is not near the bottom.
- [ ] Settings
    - Clear history
    - Set maximum amount of saved messages
    - Toggle external window
 - [ ] Docs

2024-05-22 07:19 UTC, Armored-Dragon commented
Interesting note: When testing this application I ran into seemingly random variations in the way dates are displayed. The intended way for dates to be displayed, as an example, is `[ HH:MM:SS - Month Day, Year]` or for today `[ 13:10:25 - May 22, 2024]`. This is the outcome of the date when executing the application though Steam. I use Steam as a launcher by adding the .appimage as a non Steam game.
![image](https://github.com/overte-org/overte/assets/43324896/d3e7ad04-f317-4c54-9938-727ba5c8c527)

After you submit a new message, the date will display as a different format.
![image](https://github.com/overte-org/overte/assets/43324896/2bb868cc-4db6-4c69-86ed-c787ef131304)


When executing the very same executable in a terminal, the dates come out differently. This is the result of sending a new message.
![image](https://github.com/overte-org/overte/assets/43324896/1a37fefa-5d4a-4f2f-b8e3-8e75b390bb9f)

I am not certian on the cause of this yet, but the code for creating the dates are idendical. 
If nothing else, please keep this in mind when reviewing this pull request.

2024-05-22 07:55 UTC, Armored-Dragon commented on scripts/communityScripts/armored-chat/armored_chat.qml
> +                textFormat: TextEdit.RichText
Text messages are now RichText, This could potentially cause unwanted side effects like XSS or unintended formatting.
Try pasting code into the chat when testing.

2024-05-22 10:07 UTC, Armored-Dragon commented
Despite my best efforts I have not found a reliable way to impliment "Selective auto-scroll". 

## For reviewers: 
- Please test link opening in external window. I am unable to test this myself due to #500.
- Ensure dates formats are consistant. See: https://github.com/overte-org/overte/pull/961#issuecomment-2124047419
- Are defaults acceptable? 
- [Qt RichText](https://doc.qt.io/qt-6/richtext-html-subset.html) is being used. If there is a tag that could negativly impacts the user experiance, please report.
- Are there any missing features that should be included?

2024-05-22 10:23 UTC, Armored-Dragon commented
I just remembered about the floating chat bar in referenced in #975. An alternative is not currently implimented. I will create an equivelent when I start working on this again.

2024-06-07 00:37 UTC, Armored-Dragon commented
Here is a list of tasks to do gathered from QA testing:
- [ ] Store messages in private settings to prevent ease dropping.

2024-06-07 19:42 UTC, ksuprynowicz commented
VR keyboard does not show up

2024-06-08 14:19 UTC, ksuprynowicz commented
It also looks like the messages from Floof Chat are not being received. We could drop Floof Chat compatibility later, but having no compatibility in initial version will cause problems since some people will be running stable version and some will be running development builds.
Version of Armored Chat from Community Apps is compatible with Floof Chat.

2024-06-08 16:55 UTC, Armored-Dragon commented
I've restored compatibility with floofchat in [192d80a](https://github.com/overte-org/overte/pull/961/commits/192d80aece5bc628a87afea2e0be456e9c1f7ba9), I'm hoping the the future we can toss the compatibility. Maybe after the next release?

2024-06-08 17:15 UTC, ksuprynowicz commented
> Maybe after the next release?

Sure! That's a very good idea

2024-06-20 14:37 UTC, Armored-Dragon commented
After some testing I believe it is not directly possible to invoke the VR Keyboard on overlays made using solely QML. I have gone so far as to force display the VR keyboard using Keyboard.raised by setting the value to true ([related wiki](https://apidocs.overte.org/Keyboard.html)). This method also did not work. Based on what I have seen the keyboard only (properly) displays on webengine based windows.
If anyone has any more ideas I am open to suggestions. 

In the mean time this should not be merged until the VR keyboard can get properly invoked.

2024-06-22 09:50 UTC, ksuprynowicz commented
I will try to look at VR keyboard issue this weekend

2024-07-08 08:52 UTC, ksuprynowicz requested changes
Almost everything looks good, although there's one thing that we should test thoroughly to make sure it's not a security vulnerability that could allow arbitrary JS code execution with QML priviledges.

2024-07-08 08:52 UTC, ksuprynowicz commented on scripts/communityScripts/armored-chat/armored_chat.qml
> +    }
Does the timer with 10 ms interval keep running continuously after initialization happens?

2024-07-08 08:52 UTC, ksuprynowicz commented on scripts/communityScripts/armored-chat/armored_chat.qml
> +    // }
Can we remove the commented out code?

2024-07-08 08:52 UTC, ksuprynowicz commented on scripts/communityScripts/armored-chat/armored_chat.qml
> +        mess = mess.replace(link, (match) => {return "<a onclick='Window.openUrl("+match+")' href='" + match + "'>" + match + "</a> <a onclick='Window.openUrl("+match+")'>⮺</a>"});
We should try passing HTML with JS in it at the message content and see if it could be used to run malicious JS code with QML privileges.

2024-07-08 16:23 UTC, Armored-Dragon commented on scripts/communityScripts/armored-chat/armored_chat.qml
> +        mess = mess.replace(link, (match) => {return "<a onclick='Window.openUrl("+match+")' href='" + match + "'>" + match + "</a> <a onclick='Window.openUrl("+match+")'>⮺</a>"});
Messages are displayed using QT RichText which I believe will parse string on QTs side to exclude tags not explicitly documented [here](https://doc.qt.io/qt-5/richtext-html-subset.html). If it is not in the list, it will not be rendered or executed. I tested this with an <iframe> html component linked to a local server that listens for hits. The local server never reported being accessed by anything.

Regardless, I have made a change that in effect disables all fancy tags by default. We can manually add support for tags as we need to in the future. [See this commit. ](https://github.com/overte-org/overte/pull/961/commits/6cf6e6c9ec945037690fd25667e6229b71d4845c)

2024-07-09 18:13 UTC, ksuprynowicz commented
I found such exception somehow just now, but I have trouble repeating it:
```
[07/09 20:11:59] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[07/09 20:11:59] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')" "[Error in signal proxy]"  at line  102 , column  42 Backtrace: ("TypeError: Cannot read properties of undefined (reading 'toLowerCase')", "    at receivedMessage (file:///home/ksuprynowicz/overte/overte_v8/overte/cmake-build-debug/interface/scripts/communityScripts/armored-chat/armored_chat.js:102:43)")
```

2024-07-09 18:17 UTC, ksuprynowicz commented
I also noticed that messages from FloofChat don't show up.

2024-07-09 18:18 UTC, Armored-Dragon commented
> I found such exception somehow just now, but I have trouble repeating it:
> 
> ```
> [07/09 20:11:59] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
> [07/09 20:11:59] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')" "[Error in signal proxy]"  at line  102 , column  42 Backtrace: ("TypeError: Cannot read properties of undefined (reading 'toLowerCase')", "    at receivedMessage (file:///home/ksuprynowicz/overte/overte_v8/overte/cmake-build-debug/interface/scripts/communityScripts/armored-chat/armored_chat.js:102:43)")
> ```

This seems to occur using the alternate chat application. Really any other chat application other than floofchat (also excluding this chat app of course) will cause this issue. I will put in a sanity check.
The issue is there is no "channel" key in the message object. It is trying to turn an undefined value into a lowercase string.

2024-07-09 18:34 UTC, ksuprynowicz commented on scripts/communityScripts/armored-chat/armored_chat.qml
> +        mess = mess.replace(link, (match) => {return "<a onclick='Window.openUrl("+match+")' href='" + match + "'>" + match + "</a> <a onclick='Window.openUrl("+match+")'>⮺</a>"});
Thanks! I tested it and it's indeed safe :)

2024-07-11 19:27 UTC, ksuprynowicz approved these changes

2024-07-11 19:27 UTC, merged