Fix replace avatar url option
overte-org/overte pull request #99
Opened 2022-06-21 12:57 UTC by daleglass

Fixes:

`[WARNING] [default] QCommandLineParser: option not defined: "replaceAvatarURL"`

2022-06-22 11:36 UTC, akamicah commented
It looks like changes for #95  was included in this PR also

2022-06-25 21:04 UTC, daleglass commented
PR #95 changes removed.

2022-06-25 22:54 UTC, AnimatedMannequin commented
Here are some builds you may use for testing: 

**ubuntu-18.04, full**
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.tar.Z
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.sh
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.tar.gz

**macOS-10.15, full**
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.dmg

**self-hosted_debian-11_aarch64, full**
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.sh
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.tar.gz
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.tar.Z

**windows-2019, full**
 - https://public.overte.org/build/overte/PR99/Overte-PR99-737785d.exe

2022-06-26 12:40 UTC, JulianGro requested changes
The option and the comment above don't match.
https://github.com/daleglass-overte/overte/pull/1

2022-06-27 23:01 UTC, daleglass commented
Good point, thanks!

2022-06-28 23:36 UTC, JulianGro approved these changes

2022-07-02 19:17 UTC, merged